Shader "Cairn/RibbonStrandShader"
{
    // ----------------------------------------------------------------
    // Cairn v199 — ascending strand ribbon.
    //
    // Used by:
    //   (a) Per-particle Trails Module on RingEmitter (V2.C2: no
    //       sub-emitter — Trails directly on RingEmitter, this is the
    //       trailMaterial). The trail strip is generated by Unity from
    //       particle path; we just shade it.
    //   (b) HeroRibbons mesh strips (MeshRibbonStrand.cs) — solid-mesh
    //       silhouette for distance visibility.
    //
    // Color life cycle: birth(cyan) → mid(white) → end(violet) per
    // _CairnGlobalWispBirthColor / _CairnGlobalWispMidColor /
    // _CairnGlobalWispEndColor. Vertex displacement curl noise (mesh
    // ribbon path only — particle trails use Unity's own path).
    //
    // OTA-tunable shader globals:
    //   _CairnGlobalAlpha, _CairnGlobalBloomScale,
    //   _CairnGlobalScrollMul, _CairnGlobalThermalScale,
    //   _CairnGlobalWispIntensity, _CairnGlobalWispBirthColor,
    //   _CairnGlobalWispMidColor, _CairnGlobalWispEndColor.
    //
    // Per-instance MPB (mesh ribbon path):
    //   _BirthTime, _LifecycleSec, _PhaseOffset, _RibbonHeight.
    //
    // Render: Blend One One, ZWrite Off, Queue=Transparent+10.
    // ----------------------------------------------------------------
    Properties
    {
        _BaseColor       ("Base Tint",       Color) = (1, 1, 1, 1)
        _BloomBoost      ("Bloom Boost",     Range(0.5, 5)) = 2.5
        _RibbonHeight    ("Ribbon Height m", Range(0.2, 4)) = 1.5
        _CurlAmp         ("Curl Amplitude",  Range(0, 1)) = 0.20
        _BirthTime       ("Birth Time",      Float) = 0.0
        _LifecycleSec    ("Lifecycle Sec",   Range(0.5, 10)) = 4.0
        _PhaseOffset     ("Phase Offset",    Range(0, 6.283)) = 0.0
        _InstanceAlpha   ("Instance Alpha",  Range(0, 1)) = 1.0
    }

    SubShader
    {
        Tags
        {
            "RenderType"      = "Transparent"
            "Queue"           = "Transparent+10"
            "RenderPipeline"  = "UniversalPipeline"
            "IgnoreProjector" = "True"
        }

        Blend One One
        ZWrite Off
        Cull Off

        Pass
        {
            Name "RibbonStrandForward"
            Tags { "LightMode" = "UniversalForward" }

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseColor;
                float  _BloomBoost;
                float  _RibbonHeight;
                float  _CurlAmp;
                float  _BirthTime;
                float  _LifecycleSec;
                float  _PhaseOffset;
                float  _InstanceAlpha;
            CBUFFER_END

            float  _CairnGlobalAlpha;
            float  _CairnGlobalBloomScale;
            float  _CairnGlobalScrollMul;
            float  _CairnGlobalThermalScale;
            float  _CairnGlobalWispIntensity;
            float4 _CairnGlobalWispBirthColor;
            float4 _CairnGlobalWispMidColor;
            float4 _CairnGlobalWispEndColor;

            struct Attributes
            {
                float4 positionOS : POSITION;
                float2 uv         : TEXCOORD0;
                float4 color      : COLOR;     // particle/trail color
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float2 uv         : TEXCOORD0;
                float  age01      : TEXCOORD1; // 0..1 age along trail
                float4 vCol       : COLOR;
            };

            float _coalesceR(float v) { return v > 0.0001 ? v : 1.0; }

            // Cheap 2D curl-ish noise (no texture sampler — keep mobile-cheap).
            float2 curl2(float t, float seed)
            {
                float a = sin(t * 1.7 + seed * 1.3) * 0.6
                        + sin(t * 0.7 + seed * 2.1) * 0.4;
                float b = cos(t * 1.3 + seed * 0.9) * 0.6
                        + cos(t * 0.5 + seed * 1.7) * 0.4;
                return float2(a, b);
            }

            Varyings vert(Attributes IN)
            {
                Varyings o;
                float3 pos = IN.positionOS.xyz;

                // Mesh-ribbon path: displace XZ by curl noise driven by uv.y +
                // _BirthTime + _PhaseOffset. Particle trail uses Unity's own
                // mesh — vertex shader still runs but pos.xy is already
                // emitter-space; curl displacement is added uniformly so
                // particles also get a slight wobble (visually consistent).
                float scrollMul = _coalesceR(_CairnGlobalScrollMul);
                float t = (_TimeParameters.y) * scrollMul + _PhaseOffset;
                float2 c = curl2(IN.uv.y * 4.0 + t, _PhaseOffset);
                pos.x += c.x * _CurlAmp * _CairnGlobalWispIntensity;
                pos.z += c.y * _CurlAmp * _CairnGlobalWispIntensity;
                // Ribbon height extension on uv.y — mesh ribbon authored
                // with verts at y=0; we extrude up here. For particle
                // trails Unity provides world positions and uv.y comes
                // from trail length, so this just adds vertical wobble.
                pos.y += IN.uv.y * _RibbonHeight;

                VertexPositionInputs vpi = GetVertexPositionInputs(pos);
                o.positionCS = vpi.positionCS;
                o.uv = IN.uv;
                // Mesh-ribbon: derive age from _BirthTime cycle.
                // Trail: Unity's particle COLOR.a already encodes age.
                float cycle = _LifecycleSec > 0.001 ? _LifecycleSec : 4.0;
                o.age01 = saturate(((_TimeParameters.y - _BirthTime) % cycle) / cycle);
                o.vCol = IN.color;
                return o;
            }

            float4 SampleLifeColor(float age, float4 birthC, float4 midC, float4 endC)
            {
                // 0..0.5 → birth→mid lerp, 0.5..1 → mid→end lerp.
                float4 a = lerp(birthC, midC, saturate(age * 2.0));
                float4 b = lerp(midC,   endC, saturate((age - 0.5) * 2.0));
                return age < 0.5 ? a : b;
            }

            float4 frag(Varyings IN) : SV_Target
            {
                // Lifecycle alpha: smoothstep(0, 0.15) fade-in,
                // smoothstep(0.85, 1.0) fade-out.
                float lifeAlpha = smoothstep(0.0, 0.15, IN.age01)
                                * (1.0 - smoothstep(0.85, 1.0, IN.age01));

                // Cross-ribbon falloff: alpha based on distance from
                // strip centerline (uv.x ∈ 0..1). Soft edges.
                float edge = abs(IN.uv.x - 0.5) * 2.0; // 0=center, 1=edge
                float widthAlpha = smoothstep(1.0, 0.0, edge);

                float4 lifeCol = SampleLifeColor(
                    IN.age01,
                    _CairnGlobalWispBirthColor,
                    _CairnGlobalWispMidColor,
                    _CairnGlobalWispEndColor
                );
                // Apply per-instance/particle vertex color (Unity Trails
                // Module's "Inherit Particle Color" channel — passes
                // particle gradient through COLOR).
                lifeCol *= IN.vCol;

                float bloomScale = _coalesceR(_CairnGlobalBloomScale);
                float wispInt    = _coalesceR(_CairnGlobalWispIntensity);
                float thermal    = saturate(_CairnGlobalThermalScale > 0.001 ? _CairnGlobalThermalScale : 1.0);

                float3 rgb = _BaseColor.rgb * lifeCol.rgb
                           * _BloomBoost * bloomScale * wispInt * thermal;

                float a = lifeAlpha * widthAlpha
                        * _InstanceAlpha
                        * _CairnGlobalAlpha
                        * lifeCol.a;

                return float4(rgb * a, a);
            }
            ENDHLSL
        }
    }
    Fallback Off
}
