window.REDDIT_QUOTES = {
  "rd_newzealand_0577": {
    "id": "rd_newzealand_0577",
    "theme": "beginner",
    "subreddit": "newzealand",
    "post_title": "The DOC website is INCREDIBLE",
    "title_zh": "新西兰 DOC 官网真的太牛了",
    "raw_quote": "The DOC website is INCREDIBLE\n\nAppreciation post from a Brit here. I'm coming to NZ for the first time in March and am planning to spend several weeks hiking in the Southern Alps. I've been blown away by just how great the DOC website is - access to proper maps, clear route descriptions and logistics info, easy hut booking system, integrated weather, videos walking through some of the tramps?!? \n\nI've hiked all over the UK, Ireland and Europe and normally tracking down this sort of info is a nightmare. The DOC website has my heart, I've never seen anything like it from a government agency!",
    "translation_zh": "新西兰 DOC(Department of Conservation,国家保护部,相当于国家公园管理局)官网真的太牛了\n\n一个英国人来给它写小作文。3 月要第一次去新西兰,打算在南岛的南阿尔卑斯山脉徒步几周。DOC 官网让我惊掉下巴——正儿八经的地图、清晰的路线描述加后勤信息、方便的 hut(山中过夜小屋)预订系统、天气信息集成、甚至还有一些 tramp(新西兰对多日徒步的叫法)的步道实景视频?!?\n\n我在英国、爱尔兰、欧洲各地徒步过,平常找这类信息简直是噩梦。DOC 官网让我彻底折服,从没见过哪个政府机构做出过这种东西!",
    "upvotes": 750,
    "post_url": "https://old.reddit.com/r/newzealand/comments/1qgc48w/"
  },
  "rd_backpacking_0304": {
    "id": "rd_backpacking_0304",
    "theme": "beginner",
    "subreddit": "backpacking",
    "post_title": "Backpacked thru the Ventana Wilderness for the first time last weekend.",
    "title_zh": "上周末第一次去 Ventana Wilderness 背包穿越",
    "raw_quote": "Backpacked thru the Ventana Wilderness for the first time last weekend.\n\n I don’t think I’m ever doing a normal campground here again. Cause wow a few miles inland felt so immersive. The mixture of photogenic coastlines, hill & rugged oak woodlands, lush redwoods, and steep ascents thru Kirk Creek Trail & Cone Peak was like all the best parts of California combined into one. Absolutely making a trip here again in a couple months.",
    "translation_zh": "上周末第一次去 Ventana Wilderness(加州中部一片荒野保护区)背包穿越。\n\n我觉得以后再也不来这边普通营地扎营了。往内陆走几英里就完全是另一个世界,沉浸感爆棚。上镜的海岸线、丘陵和粗犷的橡树林、郁郁葱葱的红杉、Kirk Creek Trail 和 Cone Peak 的陡上——加州所有最好的元素揉在一起。过几个月肯定还要再来一次。",
    "upvotes": 550,
    "post_url": "https://old.reddit.com/r/backpacking/comments/1ue306g/"
  },
  "rd_hiking_0281": {
    "id": "rd_hiking_0281",
    "theme": "beginner",
    "subreddit": "hiking",
    "post_title": "My first time hiking",
    "title_zh": "我的第一次徒步",
    "raw_quote": "My first time hiking\n\nWent on the hampta pass trek in India. 5  days trek with max altitude of 14k ft  through the Himalayas , it starts in green forests near jobra and ended at high altitude desert near lahul and Spiti. I enjoyed one of the best views of my life. Booked it via an organisation i found online which handled the stay and food. A bit harder than I thought but amazing views.",
    "translation_zh": "我的第一次徒步\n\n去印度走了 Hampta Pass 线,5 天穿越喜马拉雅,最高海拔 14000 英尺(约 4267 米),从 Jobra 附近的绿色森林开始,一路走到 Lahul 和 Spiti 附近的高海拔沙漠。看到了这辈子最美的景之一。我在网上找了家俱乐部,住宿吃饭都他们包了。比想象中稍难一点,但风景绝了。",
    "upvotes": 252,
    "post_url": "https://old.reddit.com/r/hiking/comments/1uigz3f/"
  },
  "rd_CampingandHiking_0445": {
    "id": "rd_CampingandHiking_0445",
    "theme": "weather",
    "subreddit": "CampingandHiking",
    "post_title": "Woke up to an ice storm on the ridge line, decided to bail",
    "title_zh": "在山脊上被冰暴叫醒,决定放弃下撤",
    "raw_quote": "Woke up to an ice storm on the ridge line, decided to bail\n\nGot a fun lesson in flexibility: had planned a week-long traverse of Taiwan's Holy Ridge, but halfway through woke up to a sudden cold front that was pushing up the Western side of the ridge line. Really high winds and below freezing temps. Decided to call it quits and hiked out the way I came. Everything on the way back was covered in rime ice, which would've been really beautiful if my hands hadn't been freezing.",
    "translation_zh": "在山脊上被冰暴叫醒,决定放弃下撤\n\n上了一堂关于「随机应变」的实战课:本来计划一周走完台湾圣稜线纵走,走到一半早上醒来发现有一股冷锋从山脊西侧突然上来。狂风加零下气温。当场决定弃走,原路撤出。回程一路上全被雾凇覆盖,要不是我手快冻掉了,那画面真的美到爆。",
    "upvotes": 2654,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/1rda8z2/"
  },
  "rd_backpacking_0741": {
    "id": "rd_backpacking_0741",
    "theme": "weather",
    "subreddit": "backpacking",
    "post_title": "A frozen night camping in Daocheng Yading, Tibet Plateau",
    "title_zh": "在青藏高原稻城亚丁露营的冻夜",
    "raw_quote": "A frozen night camping in Daocheng Yading, Tibet Plateau\n\nAfter a 10-hour bus ride from Chengdu, I reached snowy Daicheng Yading.This air, silent peaks,and a night in a sleeping bag. Freezing but surreal —-absolutely worth it",
    "translation_zh": "在青藏高原稻城亚丁露营的冻夜\n\n从成都坐 10 小时大巴,抵达雪中的稻城亚丁。这种空气、这种沉默的雪山、这种钻睡袋睡一夜的体验。冷到骨头里,但美到超现实——完全值。",
    "upvotes": 1168,
    "post_url": "https://old.reddit.com/r/backpacking/comments/1qjj09u/"
  },
  "rd_backpacking_0429": {
    "id": "rd_backpacking_0429",
    "theme": "weather",
    "subreddit": "backpacking",
    "post_title": "scared in Yosemite",
    "title_zh": "在优胜美地吓坏了",
    "raw_quote": "scared in Yosemite\n\ni usually never post but i’m honestly freaking out rn. My (22M) sister (22F) and i had this great idea to go backpacking through national parks as a graduation celebration. so far it’s been miserable and this is only night one. it snowed in Yosemite and i’m writing at 4 am, running on maybe 3-4 hrs of sleep because we’re both terrified of the bears. in an effort to avoid googling bear attack statistics and feeling worse, im turning to reddit lol. someone please reassure us that this won’t be the end 😭",
    "translation_zh": "在优胜美地吓坏了\n\n我平时不发帖的但现在真的慌。我(男 22)和我姐(女 22)想着毕业庆祝去国家公园背包穿越,结果第一晚就已经很惨。优胜美地下雪了,现在凌晨 4 点我在写这个,一共只睡了 3-4 小时,因为我俩都被熊吓死了。为了不去谷歌搜「熊袭击死亡率」把自己搞得更慌,我跑来 reddit 求安慰哈哈。求各位告诉我们这不会是我们的最后一晚 😭",
    "upvotes": 391,
    "post_url": "https://old.reddit.com/r/backpacking/comments/1tqykea/"
  },
  "rd_CampingandHiking_0427": {
    "id": "rd_CampingandHiking_0427",
    "theme": "solo_fear",
    "subreddit": "CampingandHiking",
    "post_title": "On a solo hike in central MA this weekend when suddenly two strange, unleashed dogs came tearing through the woods and started circling me while barking and snarling. The owners eventually sauntered up and chuckled at me for being scared. My thoughts...",
    "title_zh": "周末马萨诸塞州中部独自徒步,突然两只没牵绳的陌生狗冲过来围着我狂吠露牙。主人慢悠悠走过来,还笑话我怕。我想说……",
    "raw_quote": "On a solo hike in central MA this weekend when suddenly two strange, unleashed dogs came tearing through the woods and started circling me while barking and snarling. The owners eventually sauntered up and chuckled at me for being scared. My thoughts...",
    "translation_zh": "周末我在马萨诸塞州(MA)中部独自徒步,突然两只陌生的、没牵绳的狗从林子里冲出来,围着我打转,又叫又露牙咆哮。狗主人过了好一会儿才慢慢晃过来,还笑我这么害怕。我想说的是……",
    "upvotes": 850,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/3j45gv/"
  },
  "rd_hiking_0700": {
    "id": "rd_hiking_0700",
    "theme": "lost",
    "subreddit": "hiking",
    "post_title": "Started wearing emergency device on solo hikes and it changed my mindset",
    "title_zh": "开始独自徒步带紧急呼救设备,心态整个变了",
    "raw_quote": "Started wearing emergency device on solo hikes and it changed my mindset\n\nI'm 69 and hike alone most mornings but family started worrying after a friend got lost on a trail for 8 hours. Decided to try bay alarm since it has GPS and works away from cell towers. First few hikes felt weird having this safety net but now I actually hike further and try more challenging trails because I know help is available if needed. The psychological shift surprised me more than the technology. Having backup made me more adventurous, not more cautious like I expected.",
    "translation_zh": "开始独自徒步带紧急呼救设备,心态整个变了\n\n我 69 岁,大多数早上都自己去徒步。前段时间有个朋友在步道上迷路 8 小时,家人开始不放心。我就试了下 bay alarm(一款带 GPS、脱离蜂窝信号也能用的紧急呼救设备,类似 PLB 个人定位信标)。头几次戴着这个「安全网」感觉挺怪的,但现在我反而走得更远,敢去尝试更难的路线,因为知道真出事有人能救。心态上的变化比技术本身更让我意外。有了 backup,我变得更爱冒险,而不是像我以为的那样更谨慎。",
    "upvotes": 163,
    "post_url": "https://old.reddit.com/r/hiking/comments/1oi36xj/"
  },
  "rd_CampingandHiking_0172": {
    "id": "rd_CampingandHiking_0172",
    "theme": "solo_fear",
    "subreddit": "CampingandHiking",
    "post_title": "Some of my last solo/duo hike and camping Switzerland.",
    "title_zh": "最近在瑞士的一些单人/双人徒步露营",
    "raw_quote": "Some of my last solo/duo hike and camping Switzerland.\n\nSwitzerland lake of Robiei, lake of Tom, Naret, Liguria punta chiappa. \n\nStarted to enjoy solo camping, lot of lakes here’s over 2k meters. I’m from Switzerland Ticino. \n\nWaiting for last couple things before trying a 2 night solo 🏔️🫣",
    "translation_zh": "最近在瑞士的一些单人/双人徒步露营。\n\n瑞士 Robiei 湖、Tom 湖、Naret 湖,还有意大利利古里亚的 Punta Chiappa。\n\n开始享受单人露营了,这一带海拔 2000 米以上的湖非常多。我是瑞士提契诺(Ticino,意大利语区)人。\n\n还在等最后几件装备到位,准备试试 2 晚单人露营 🏔️🫣",
    "upvotes": 157,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/1tqddus/"
  },
  "rd_newzealand_0254": {
    "id": "rd_newzealand_0254",
    "theme": "river",
    "subreddit": "newzealand",
    "post_title": "PSA The Waimakariri River has run out of water",
    "title_zh": "重要提示:Waimakariri 河已经没水了",
    "raw_quote": "PSA The Waimakariri River has run out of water\n\nInland from the Bealey bridge the river just disappears and there's barely any evidence there has been water there with no water in the low spots and barely any mud.  \n\nI went prepared for river crossings and instead found no water.  \n\nI have some theories as to what's going on, but with no evidence it's purely speculation.   \n\nAny wild theories?",
    "translation_zh": "重要提示(PSA=Public Service Announcement,公众提醒):Waimakariri 河已经没水了\n\n从 Bealey 大桥往内陆走,河就直接消失了,几乎看不出这里曾经有过水——低洼处没水,连泥都几乎没有。\n\n我做好了涉水过河的准备,结果发现根本没水。\n\n我有一些猜想在解释怎么回事,但没证据纯属瞎猜。\n\n谁有更野的解释?",
    "upvotes": 603,
    "post_url": "https://old.reddit.com/r/newzealand/comments/1d0tgka/"
  },
  "rd_hiking_0953": {
    "id": "rd_hiking_0953",
    "theme": "river",
    "subreddit": "hiking",
    "post_title": "Today on Lake Pettit Trail in Idaho, USA",
    "title_zh": "今天在美国爱达荷州 Lake Pettit 步道",
    "raw_quote": "Today on Lake Pettit Trail in Idaho, USA\n\nSo glad I decided to spend a few days in the Sawtooth Mountains.  Today I hiked to Alice Lake.  Beautiful and not particularly difficult.  15 miles and 2100 feet vertical.  You'll have some easy river crossings to do and, depending on the routes you take you might have to contend with a lot of deadfall.",
    "translation_zh": "今天在美国爱达荷州 Lake Pettit 步道\n\n幸好当初决定来 Sawtooth 山脉待几天。今天走到了 Alice Lake。景美,难度也不算大。15 英里、爬升 2100 英尺(约 640 米)。路上会有几处轻松的过河,看你走哪条支线,可能会碰到不少倒树。",
    "upvotes": 151,
    "post_url": "https://old.reddit.com/r/hiking/comments/1unrdw8/"
  },
  "rd_tramping_0191": {
    "id": "rd_tramping_0191",
    "theme": "river",
    "subreddit": "tramping",
    "post_title": "Rees-Dart Track snowy creek river crossing?",
    "title_zh": "Rees-Dart 步道 Snowy Creek 过河怎么办?",
    "raw_quote": "Rees-Dart Track snowy creek river crossing?\n\nHey Everyone, has anyone here crossed the Upper Snowy Creek when no bridge is installed?\n\nIs it still sketchy even when the weather is fine?\n\nI'm doing Rees Dart on November 12, and it's looking like the bridge won't be installed in time. How stupid is it to cross the river in good conditions?",
    "translation_zh": "Rees-Dart 步道 Snowy Creek 过河怎么办?\n\n大家好,有人在桥还没装上的时候过过 Upper Snowy Creek 上游吗?\n\n即使天气好,过起来是不是还是很险?\n\n我 11 月 12 日要走 Rees-Dart(新西兰南岛一条经典 tramp 线),看样子桥装不上了。天气好的时候硬过,是不是很脑残?",
    "upvotes": 29,
    "post_url": "https://old.reddit.com/r/tramping/comments/1o7ps8u/"
  },
  "rd_CampingandHiking_0062": {
    "id": "rd_CampingandHiking_0062",
    "theme": "lost",
    "subreddit": "CampingandHiking",
    "post_title": "Our spot in the Bitterroot this week. A search and rescue helicopter paid us a visit on Friday- apparently somebody was lost for 5 days in the same wilderness we were in, and was found alive just 3 days ago! 😮",
    "title_zh": "这周我们在 Bitterroot 的营地。周五一架搜救直升机来了一趟——原来有个人在我们所在的同一片荒野里失踪了 5 天,3 天前才被活着找到! 😮",
    "raw_quote": "Our spot in the Bitterroot this week. A search and rescue helicopter paid us a visit on Friday- apparently somebody was lost for 5 days in the same wilderness we were in, and was found alive just 3 days ago! 😮",
    "translation_zh": "这周我们在 Bitterroot(蒙大拿-爱达荷州交界的野地)扎营。周五一架 SAR(Search and Rescue,搜救)直升机飞过来看了我们一眼——原来就在我们所在的同一片荒野,有个人失踪了 5 天,3 天前才被活着救回! 😮",
    "upvotes": 80,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/csk7ps/"
  },
  "rd_backpacking_0508": {
    "id": "rd_backpacking_0508",
    "theme": "lost",
    "subreddit": "backpacking",
    "post_title": "Backcountry 5 nighter in Banff last summer. We were told we wouldn’t run into any snow. Woke up to a fresh coat, hiked through a hail storm, realized we should’ve bought gaiters, got lost for a while, ended up hiking at least 16 miles before making it to the site at dark. Worth it",
    "title_zh": "去年夏天班夫野地 5 晚穿越。人家跟我们说不会遇到雪。结果醒来一层新雪、穿越冰雹暴、才发现该买雪套(gaiters)、迷了一阵路、最后至少走了 16 英里天黑才到营地。但值",
    "raw_quote": "Backcountry 5 nighter in Banff last summer. We were told we wouldn’t run into any snow. Woke up to a fresh coat, hiked through a hail storm, realized we should’ve bought gaiters, got lost for a while, ended up hiking at least 16 miles before making it to the site at dark. Worth it",
    "translation_zh": "去年夏天在班夫(Banff 国家公园,加拿大)走了 5 晚的 backcountry(无维护的野外区,不同于步道营地)。当时被告知不会遇到雪。结果一早醒来盖了一层新雪,穿越冰雹风暴,意识到当初该买雪套(gaiters,防雪进鞋的绑腿),中途迷路了一阵,最后至少走了 16 英里,天黑才到营地。但值。",
    "upvotes": 55,
    "post_url": "https://old.reddit.com/r/backpacking/comments/eziwj6/"
  },
  "rd_CampingandHiking_0058": {
    "id": "rd_CampingandHiking_0058",
    "theme": "rescue",
    "subreddit": "CampingandHiking",
    "post_title": "Our rescue doggo Bruno enjoyed his camping trip. Two happy days and nights filled with hiking and swimming in the North Cascades / Mount Baker Wilderness. It's safe to say he's a big fan. Already looking forward to his next trip!",
    "title_zh": "我们领养的救助犬 Bruno 露营玩得很开心。两天两夜在北喀斯喀特 / 贝克山荒野徒步游泳。可以说它已经是死忠粉了。已经在期待下次!",
    "raw_quote": "Our rescue doggo Bruno enjoyed his camping trip. Two happy days and nights filled with hiking and swimming in the North Cascades / Mount Baker Wilderness. It's safe to say he's a big fan. Already looking forward to his next trip!",
    "translation_zh": "我们家的救助犬(rescue dog,从收容所领养来的狗)Bruno 露营玩得超开心。在 North Cascades / Mount Baker Wilderness(华盛顿州北部荒野)徒步加游泳两天两夜。可以说它已经彻底爱上露营了。已经在盼下一次!",
    "upvotes": 1036,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/i5l9ji/"
  },
  "rd_newzealand_0628": {
    "id": "rd_newzealand_0628",
    "theme": "rescue",
    "subreddit": "newzealand",
    "post_title": "It has begun. There is a towel on the line that will never get dry, the winter never ending rains have begun, and it will hang forelorn and with dwindling hope of ever being rescued. All other towels are giving it the smug finger from the dryer.",
    "title_zh": "冬天来了。晾衣绳上有一条毛巾永远晾不干,那种下不完的冬雨开始了,它就那样孤零零地挂着,越来越没希望被「营救」下来。烘干机里的其他毛巾都在得意地对它比中指。",
    "raw_quote": "It has begun. There is a towel on the line that will never get dry, the winter never ending rains have begun, and it will hang forelorn and with dwindling hope of ever being rescued. All other towels are giving it the smug finger from the dryer.",
    "translation_zh": "开始了。晾衣绳上有一条毛巾再也晾不干了,新西兰那种下不完的冬雨已经登场,它孤单地挂在那里,被「营救」进屋的希望一天天渺茫。烘干机里的其他毛巾都在得意洋洋对它竖中指。",
    "upvotes": 874,
    "post_url": "https://old.reddit.com/r/newzealand/comments/8czex7/"
  },
  "rd_newzealand_0616": {
    "id": "rd_newzealand_0616",
    "theme": "rescue",
    "subreddit": "newzealand",
    "post_title": "Maori troops line up on the quayside at Alexandria in Egypt following their evacuation from Crete, 3 June 1941. Between 28 May and 1 June 1941, 18,000 Australian, New Zealand and British troops were rescued by the Royal Navy following a week of bitter fighting against German Fallschirmjäger.",
    "title_zh": "1941 年 6 月 3 日,毛利部队从克里特岛撤退后在埃及亚历山大港码头列队。1941 年 5 月 28 日至 6 月 1 日,在与德国伞兵激战一周后,18000 名澳大利亚、新西兰、英国士兵被英国皇家海军救出。",
    "raw_quote": "Maori troops line up on the quayside at Alexandria in Egypt following their evacuation from Crete, 3 June 1941. Between 28 May and 1 June 1941, 18,000 Australian, New Zealand and British troops were rescued by the Royal Navy following a week of bitter fighting against German Fallschirmjäger.",
    "translation_zh": "1941 年 6 月 3 日,毛利部队从克里特岛撤退后在埃及亚历山大港码头列队。1941 年 5 月 28 日至 6 月 1 日期间,在与德军伞兵(Fallschirmjäger,德语「伞兵」)激战一周后,共有 18000 名澳大利亚、新西兰和英国士兵被英国皇家海军救出。",
    "upvotes": 289,
    "post_url": "https://old.reddit.com/r/newzealand/comments/l0upta/"
  },
  "rd_newzealand_0016": {
    "id": "rd_newzealand_0016",
    "theme": "gear",
    "subreddit": "newzealand",
    "post_title": "Tramping/Hiking NZ - Blister prevention",
    "title_zh": "新西兰徒步 - 怎么防水泡?",
    "raw_quote": "Tramping/Hiking NZ - Blister prevention\n\nHello,\n\nI am going on a 4 day hike soon, and want to pack for blister prevention. I'd like to get some tape, should I develop some hotspots on my feet from my tramping boots.  Could anyone please recommend what to buy in NZ, please?\n\nThank you.",
    "translation_zh": "新西兰 tramping(多日徒步)/hiking - 怎么防水泡?\n\n大家好,\n\n我很快要去 4 天徒步,想带点防水泡的东西。想买点胶带,万一被登山靴磨出「热点」(hotspot,水泡形成前皮肤发热发红的先兆)可以贴一下。有人能推荐一下在新西兰能买到的什么牌子吗?\n\n谢谢。",
    "upvotes": 0,
    "post_url": "https://old.reddit.com/r/newzealand/comments/1ghncu1/"
  },
  "rd_hiking_1188": {
    "id": "rd_hiking_1188",
    "theme": "gear",
    "subreddit": "hiking",
    "post_title": "Blister Party",
    "title_zh": "水泡派对",
    "raw_quote": "Blister Party\n\nObviously getting a lot of time in hiking and/or training will help prevent blisters in the long run, but what are some of the easier and better options to dealing with a blister 10 miles into a 20 mile hike?",
    "translation_zh": "水泡派对\n\n显然长期看,多走多训练能减少起泡。但如果 20 英里徒步走到第 10 英里刚好起了水泡,当场比较简单且有效的处理办法有哪些?",
    "upvotes": 9,
    "post_url": "https://old.reddit.com/r/hiking/comments/1crmji/"
  },
  "rd_hiking_1137": {
    "id": "rd_hiking_1137",
    "theme": "gear",
    "subreddit": "hiking",
    "post_title": "Blister under big toe nail",
    "title_zh": "大脚趾指甲下面起水泡了",
    "raw_quote": "Blister under big toe nail\n\nI do a 30 mile hike every year for the CF Foundation and every year I kill 2-3 toenails doing it.  This year the nail I thought was dead (loose and uncomfortable) had a blister underneath it.  I trimmed it and it started leaking, which at first felt better, but not so much now.\n\nSo, my question, what tips do you have saving your toenails?  My boots are well broken in and fit well.  I change socks every 10 miles. Short hikes <15 miles don't bother me.",
    "translation_zh": "大脚趾指甲下面起水泡了\n\n我每年为 CF 基金会(囊性纤维化基金会)做一次 30 英里公益徒步,每年都会「牺牲」2-3 片脚指甲。今年有一片指甲我以为已经死透了(松、不舒服),结果下面居然还长了水泡。我把它修剪掉后开始漏液,一开始还挺爽,但现在越来越难受。\n\n所以问一下,大家有什么保护脚指甲的技巧?靴子磨合得很好、鞋号也合适。每 10 英里换一次袜子。15 英里以内的短徒步就完全不磨。",
    "upvotes": 8,
    "post_url": "https://old.reddit.com/r/hiking/comments/1fq9z00/"
  },
  "rd_CampingandHiking_0553": {
    "id": "rd_CampingandHiking_0553",
    "theme": "plan_gear_advice",
    "subreddit": "CampingandHiking",
    "post_title": "Looking for gear advice as a broke high schooler",
    "title_zh": "穷高中生求装备建议",
    "raw_quote": "Looking for gear advice as a broke high schooler\n\nAs the title said: I’m looking for advice. I’m planning a 3-4 day trip through a wooded area with no infrastructure in it. I already have the ground work for my gear but feel like I’m missing a lot. While writing this I’ve already realized I forgot a folding spade, toilet paper, my thermal layers and my stakes for the tarp. This will be my first trip that isn’t a single night so any suggestions for meals would be much appreciated. Thank you and happy hiking!",
    "translation_zh": "穷高中生求装备建议\n\n如题:求点建议。计划 3-4 天穿越一片没有任何基础设施的林地。基本装备我大致备齐了,但感觉还缺一堆。写着写着就已经想起来我忘了折叠工兵铲、卫生纸、保暖层、还有防水布(tarp)的地钉。这将是我第一次多晚露营,所以关于餐食有任何建议都非常感谢。谢谢大家,徒步愉快!",
    "upvotes": 218,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/1rihchj/"
  },
  "rd_backpacking_1023": {
    "id": "rd_backpacking_1023",
    "theme": "plan_gear_advice",
    "subreddit": "backpacking",
    "post_title": "Gear list suggestions.",
    "title_zh": "装备清单求建议",
    "raw_quote": "Gear list suggestions.\n\nI made my own personalized gear list checklist. I’ve been on 4 backpacking trips, so still new to this. Wanting to get some feedback on what to bring, anything I’m missing or should get rid of to lighten my pack? \n\nMind you I am an EMT so my medical bag does have more than the average person, but I can probably clean it up a little bit and bring less.",
    "translation_zh": "装备清单求建议\n\n我自己做了一份个人装备 checklist。到目前只出过 4 次 backpacking(多日背包穿越),还算新手。想让大家看看我该带什么、有什么漏了、有什么可以砍掉减重的?\n\n注:我是 EMT(急救医疗技术员),所以医疗包比普通人多不少东西,但我应该可以再精简一点。",
    "upvotes": 83,
    "post_url": "https://old.reddit.com/r/backpacking/comments/1u9sn87/"
  },
  "rd_CampingandHiking_1064": {
    "id": "rd_CampingandHiking_1064",
    "theme": "plan_gear_advice",
    "subreddit": "CampingandHiking",
    "post_title": "How do you deal with water when backpacking/snowmobiling in cold weather?",
    "title_zh": "冬天背包穿越 / 玩雪地摩托,水怎么办?",
    "raw_quote": "How do you deal with water when backpacking/snowmobiling in cold weather?\n\nMe and my friends have done winter camping with winter tents and heater so the water freezing was never a concern. But, how would you do it when travelling large distances? Do you find you water sacks freeze? Is it more practical just to boil/filter snow? \n\n\nAny winter gear recommendations are appreciated too!\n\nThanks!",
    "translation_zh": "冬天 backpacking / 雪地摩托出行,饮用水怎么解决?\n\n我和朋友之前冬天露营都是用冬季帐 + 帐篷加热器,所以水结冰这事一直不是问题。但如果是要长距离移动的情况怎么办?你们的水袋(water bladder,背包内置的软水囊)会冻住吗?是不是直接烧雪 / 过滤雪水更实际?\n\n顺便求任何冬季装备推荐!\n\n谢谢!",
    "upvotes": 69,
    "post_url": "https://old.reddit.com/r/CampingandHiking/comments/1188muw/"
  }
};