import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shared__tab_bar: {
    position: 'absolute',
    left: 24,
    top: 730,
    width: 327,
    height: 62,
    backgroundColor: 'rgba(247,243,234,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.12)',
    borderRadius: 31,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  shared__tab_bar__tab_trails: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_trails_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_label: {
    color: '#0F5D45',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  shared__tab_bar__tab_friends: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_friends_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  shared__tab_bar__tab_memory: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_memory_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  shared__tab_bar__tab_settings: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_settings_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  R0__seg_container: {
    position: 'absolute',
    left: 24,
    top: 56,
    width: 327,
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 20,
  },
  R0__seg_container__seg_activities: {
    position: 'absolute',
    left: 4,
    top: 4,
    width: 105,
    height: 32,
    backgroundColor: '#143D35',
    borderRadius: 16,
  },
  R0__seg_container__seg_activities__lbl: {
    position: 'absolute',
    left: 0,
    top: 10,
    width: 105,
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R0__seg_container__seg_routes: {
    position: 'absolute',
    left: 128,
    top: 14,
    width: 71,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
  },
  R0__seg_container__seg_cairns: {
    position: 'absolute',
    left: 218,
    top: 14,
    width: 71,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
  },
  R0__chip_all: {
    position: 'absolute',
    left: 24,
    top: 112,
    width: 46,
    height: 30,
    backgroundColor: '#143D35',
    borderRadius: 15,
  },
  R0__chip_all__lbl: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 46,
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R0__chip_hiking: {
    position: 'absolute',
    left: 78,
    top: 112,
    width: 70,
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 15,
  },
  R0__chip_hiking__lbl: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 70,
    fontSize: 12,
    color: '#3F4A44',
    fontWeight: '600',
    textAlign: 'center',
  },
  R0__chip_running: {
    position: 'absolute',
    left: 156,
    top: 112,
    width: 78,
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 15,
  },
  R0__chip_running__lbl: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 78,
    fontSize: 12,
    color: '#3F4A44',
    fontWeight: '600',
    textAlign: 'center',
  },
  R0__chip_recent: {
    position: 'absolute',
    left: 242,
    top: 112,
    width: 74,
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 15,
  },
  R0__chip_recent__lbl: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 74,
    fontSize: 12,
    color: '#3F4A44',
    fontWeight: '600',
    textAlign: 'center',
  },
  R0__row_1: {
    position: 'absolute',
    left: 24,
    top: 162,
    width: 327,
    height: 56,
  },
  R0__row_1__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_1__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_1__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_2: {
    position: 'absolute',
    left: 24,
    top: 222,
    width: 327,
    height: 56,
  },
  R0__row_2__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_2__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_2__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_3: {
    position: 'absolute',
    left: 24,
    top: 282,
    width: 327,
    height: 56,
  },
  R0__row_3__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_3__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_3__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_4: {
    position: 'absolute',
    left: 24,
    top: 342,
    width: 327,
    height: 56,
  },
  R0__row_4__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_4__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_4__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_5: {
    position: 'absolute',
    left: 24,
    top: 402,
    width: 327,
    height: 56,
  },
  R0__row_5__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_5__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_5__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_6: {
    position: 'absolute',
    left: 24,
    top: 462,
    width: 327,
    height: 56,
  },
  R0__row_6__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_6__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_6__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_7: {
    position: 'absolute',
    left: 24,
    top: 522,
    width: 327,
    height: 56,
  },
  R0__row_7__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_7__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_7__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__row_8: {
    position: 'absolute',
    left: 24,
    top: 582,
    width: 327,
    height: 56,
  },
  R0__row_8__icon: {
    position: 'absolute',
    left: 0,
    top: 8,
    width: 40,
    height: 40,
  },
  R0__row_8__title: {
    position: 'absolute',
    left: 52,
    top: 6,
    width: 240,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__row_8__meta: {
    position: 'absolute',
    left: 52,
    top: 28,
    width: 250,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
  },
  R0__footer_mountains: {
    position: 'absolute',
    left: 0,
    top: 640,
    width: 375,
    height: 80,
  },
  R1__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R1__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 340,
    backgroundColor: '#E8E3D3',
  },
  R1__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 160,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R1__sheet: {
    position: 'absolute',
    left: 0,
    top: 430,
    width: 375,
    height: 300,
    backgroundColor: '#F7F3EA',
    borderRadius: 24,
  },
  R1__sheet__title: {
    position: 'absolute',
    left: 24,
    top: 30,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
  },
  R1__sheet__edit: {
    position: 'absolute',
    left: 172,
    top: 34,
    fontSize: 16,
    color: '#65706A',
  },
  R1__sheet__stat1_v: {
    position: 'absolute',
    left: 24,
    top: 82,
    width: 90,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R1__sheet__stat1_l: {
    position: 'absolute',
    left: 24,
    top: 110,
    width: 90,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R1__sheet__stat2_v: {
    position: 'absolute',
    left: 142,
    top: 82,
    width: 90,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R1__sheet__stat2_l: {
    position: 'absolute',
    left: 142,
    top: 110,
    width: 90,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R1__sheet__stat3_v: {
    position: 'absolute',
    left: 260,
    top: 82,
    width: 90,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R1__sheet__stat3_l: {
    position: 'absolute',
    left: 260,
    top: 110,
    width: 90,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R1__sheet__meta_row: {
    position: 'absolute',
    left: 24,
    top: 154,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '500',
  },
  R1__sheet__btn_delete: {
    position: 'absolute',
    left: 24,
    top: 210,
    width: 100,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: '#C64B4B',
    borderRadius: 22,
  },
  R1__sheet__btn_delete__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 100,
    fontSize: 14,
    color: '#C64B4B',
    fontWeight: '700',
    textAlign: 'center',
  },
  R1__sheet__btn_save: {
    position: 'absolute',
    left: 134,
    top: 210,
    width: 217,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R1__sheet__btn_save__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 217,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R2__seg_container: {
    position: 'absolute',
    left: 24,
    top: 56,
    width: 327,
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 20,
  },
  R2__seg_container__seg_activities: {
    position: 'absolute',
    left: 4,
    top: 14,
    width: 105,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
  },
  R2__seg_container__seg_routes: {
    position: 'absolute',
    left: 111,
    top: 4,
    width: 105,
    height: 32,
    backgroundColor: '#143D35',
    borderRadius: 16,
  },
  R2__seg_container__seg_routes__lbl: {
    position: 'absolute',
    left: 0,
    top: 10,
    width: 105,
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R2__seg_container__seg_cairns: {
    position: 'absolute',
    left: 218,
    top: 14,
    width: 71,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
  },
  R2__subtab_mine: {
    position: 'absolute',
    left: 0,
    top: 118,
    width: 187,
    fontSize: 14,
    color: '#0F5D45',
    fontWeight: '700',
    textAlign: 'center',
  },
  R2__subtab_mine_underline: {
    position: 'absolute',
    left: 66,
    top: 138,
    width: 60,
    height: 3,
    backgroundColor: '#0F5D45',
    borderRadius: 2,
  },
  R2__subtab_friends: {
    position: 'absolute',
    left: 187,
    top: 118,
    width: 187,
    fontSize: 14,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R2__route_row_1: {
    position: 'absolute',
    left: 24,
    top: 162,
    width: 327,
    height: 68,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R2__route_row_1__thumb: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 44,
    height: 44,
    backgroundColor: '#F4EFE6',
    borderRadius: 10,
  },
  R2__route_row_1__title: {
    position: 'absolute',
    left: 68,
    top: 14,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R2__route_row_1__meta: {
    position: 'absolute',
    left: 68,
    top: 36,
    fontSize: 12,
    color: '#65706A',
  },
  R2__route_row_1__chev: {
    position: 'absolute',
    left: 295,
    top: 22,
    fontSize: 22,
    color: '#8A8579',
  },
  R2__route_row_2: {
    position: 'absolute',
    left: 24,
    top: 240,
    width: 327,
    height: 68,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R2__route_row_2__thumb: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 44,
    height: 44,
    backgroundColor: '#F4EFE6',
    borderRadius: 10,
  },
  R2__route_row_2__title: {
    position: 'absolute',
    left: 68,
    top: 14,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R2__route_row_2__meta: {
    position: 'absolute',
    left: 68,
    top: 36,
    fontSize: 12,
    color: '#65706A',
  },
  R2__route_row_2__chev: {
    position: 'absolute',
    left: 295,
    top: 22,
    fontSize: 22,
    color: '#8A8579',
  },
  R2__route_row_3: {
    position: 'absolute',
    left: 24,
    top: 318,
    width: 327,
    height: 68,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R2__route_row_3__thumb: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 44,
    height: 44,
    backgroundColor: '#F4EFE6',
    borderRadius: 10,
  },
  R2__route_row_3__title: {
    position: 'absolute',
    left: 68,
    top: 14,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R2__route_row_3__meta: {
    position: 'absolute',
    left: 68,
    top: 36,
    fontSize: 12,
    color: '#65706A',
  },
  R2__route_row_3__chev: {
    position: 'absolute',
    left: 295,
    top: 22,
    fontSize: 22,
    color: '#8A8579',
  },
  R2__route_row_4: {
    position: 'absolute',
    left: 24,
    top: 396,
    width: 327,
    height: 68,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R2__route_row_4__thumb: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 44,
    height: 44,
    backgroundColor: '#F4EFE6',
    borderRadius: 10,
  },
  R2__route_row_4__title: {
    position: 'absolute',
    left: 68,
    top: 14,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R2__route_row_4__meta: {
    position: 'absolute',
    left: 68,
    top: 36,
    fontSize: 12,
    color: '#65706A',
  },
  R2__route_row_4__chev: {
    position: 'absolute',
    left: 295,
    top: 22,
    fontSize: 22,
    color: '#8A8579',
  },
  R2__route_row_5: {
    position: 'absolute',
    left: 24,
    top: 474,
    width: 327,
    height: 68,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R2__route_row_5__thumb: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 44,
    height: 44,
    backgroundColor: '#F4EFE6',
    borderRadius: 10,
  },
  R2__route_row_5__title: {
    position: 'absolute',
    left: 68,
    top: 14,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R2__route_row_5__meta: {
    position: 'absolute',
    left: 68,
    top: 36,
    fontSize: 12,
    color: '#65706A',
  },
  R2__route_row_5__chev: {
    position: 'absolute',
    left: 295,
    top: 22,
    fontSize: 22,
    color: '#8A8579',
  },
  R2__route_row_6: {
    position: 'absolute',
    left: 24,
    top: 552,
    width: 327,
    height: 68,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R2__route_row_6__thumb: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 44,
    height: 44,
    backgroundColor: '#F4EFE6',
    borderRadius: 10,
  },
  R2__route_row_6__title: {
    position: 'absolute',
    left: 68,
    top: 14,
    fontSize: 15,
    color: '#202A25',
    fontWeight: '700',
  },
  R2__route_row_6__meta: {
    position: 'absolute',
    left: 68,
    top: 36,
    fontSize: 12,
    color: '#65706A',
  },
  R2__route_row_6__chev: {
    position: 'absolute',
    left: 295,
    top: 22,
    fontSize: 22,
    color: '#8A8579',
  },
  R2__footer_mountains: {
    position: 'absolute',
    left: 0,
    top: 640,
    width: 375,
    height: 80,
  },
  R3__seg_container: {
    position: 'absolute',
    left: 24,
    top: 56,
    width: 327,
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 20,
  },
  R3__seg_container__seg_activities: {
    position: 'absolute',
    left: 4,
    top: 14,
    width: 105,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
  },
  R3__seg_container__seg_routes: {
    position: 'absolute',
    left: 111,
    top: 4,
    width: 105,
    height: 32,
    backgroundColor: '#143D35',
    borderRadius: 16,
  },
  R3__seg_container__seg_routes__lbl: {
    position: 'absolute',
    left: 0,
    top: 10,
    width: 105,
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R3__seg_container__seg_cairns: {
    position: 'absolute',
    left: 218,
    top: 14,
    width: 71,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
  },
  R3__subtab_mine: {
    position: 'absolute',
    left: 0,
    top: 118,
    width: 187,
    fontSize: 14,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R3__subtab_friends: {
    position: 'absolute',
    left: 187,
    top: 118,
    width: 187,
    fontSize: 14,
    color: '#0F5D45',
    fontWeight: '700',
    textAlign: 'center',
  },
  R3__subtab_friends_underline: {
    position: 'absolute',
    left: 250,
    top: 138,
    width: 66,
    height: 3,
    backgroundColor: '#0F5D45',
    borderRadius: 2,
  },
  R3__hero_illust: {
    position: 'absolute',
    left: 76,
    top: 210,
    width: 224,
    height: 220,
  },
  R3__empty_title: {
    position: 'absolute',
    left: 0,
    top: 460,
    width: 375,
    fontSize: 17,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R3__empty_sub: {
    position: 'absolute',
    left: 30,
    top: 492,
    width: 315,
    fontSize: 13,
    color: '#65706A',
    fontWeight: '500',
    lineHeight: 20,
    textAlign: 'center',
  },
  R3__footer_mountains: {
    position: 'absolute',
    left: 0,
    top: 640,
    width: 375,
    height: 80,
  },
  R4__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R4__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 320,
    backgroundColor: '#E8E3D3',
  },
  R4__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 150,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R4__sheet: {
    position: 'absolute',
    left: 0,
    top: 420,
    width: 375,
    height: 310,
    backgroundColor: '#F7F3EA',
    borderRadius: 24,
  },
  R4__sheet__title: {
    position: 'absolute',
    left: 24,
    top: 30,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
  },
  R4__sheet__edit: {
    position: 'absolute',
    left: 172,
    top: 34,
    fontSize: 16,
    color: '#65706A',
  },
  R4__sheet__stat1_v: {
    position: 'absolute',
    left: 24,
    top: 82,
    width: 90,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R4__sheet__stat1_l: {
    position: 'absolute',
    left: 24,
    top: 110,
    width: 90,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R4__sheet__stat2_v: {
    position: 'absolute',
    left: 142,
    top: 82,
    width: 90,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R4__sheet__stat2_l: {
    position: 'absolute',
    left: 142,
    top: 110,
    width: 90,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R4__sheet__stat3_v: {
    position: 'absolute',
    left: 260,
    top: 82,
    width: 90,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
  },
  R4__sheet__stat3_l: {
    position: 'absolute',
    left: 260,
    top: 110,
    width: 90,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R4__sheet__btn_edit: {
    position: 'absolute',
    left: 24,
    top: 156,
    width: 327,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R4__sheet__btn_edit__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R4__sheet__btn_delete: {
    position: 'absolute',
    left: 24,
    top: 212,
    width: 327,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: '#C64B4B',
    borderRadius: 22,
  },
  R4__sheet__btn_delete__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 14,
    color: '#C64B4B',
    fontWeight: '700',
    textAlign: 'center',
  },
  R5__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R5__title: {
    position: 'absolute',
    left: 0,
    top: 56,
    width: 375,
    fontSize: 17,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R5__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 440,
    backgroundColor: '#E8E3D3',
  },
  R5__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 210,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R5__toolbar: {
    position: 'absolute',
    left: 24,
    top: 552,
    width: 327,
    height: 76,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 18,
  },
  R5__toolbar__tool_beautify: {
    position: 'absolute',
    left: 8,
    top: 8,
    width: 78,
    height: 60,
  },
  R5__toolbar__tool_beautify__icon_bg: {
    position: 'absolute',
    left: 25,
    top: 6,
    width: 28,
    height: 28,
    backgroundColor: '#F4EFE6',
    borderRadius: 14,
  },
  R5__toolbar__tool_beautify__icon_bg__ico: {
    position: 'absolute',
    left: 0,
    top: 6,
    width: 28,
    fontSize: 15,
    color: '#0F5D45',
    textAlign: 'center',
  },
  R5__toolbar__tool_beautify__lbl: {
    position: 'absolute',
    left: 0,
    top: 40,
    width: 78,
    fontSize: 11,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R5__toolbar__tool_trim: {
    position: 'absolute',
    left: 86,
    top: 8,
    width: 78,
    height: 60,
  },
  R5__toolbar__tool_trim__icon_bg: {
    position: 'absolute',
    left: 25,
    top: 6,
    width: 28,
    height: 28,
    backgroundColor: '#F4EFE6',
    borderRadius: 14,
  },
  R5__toolbar__tool_trim__icon_bg__ico: {
    position: 'absolute',
    left: 0,
    top: 6,
    width: 28,
    fontSize: 15,
    color: '#0F5D45',
    textAlign: 'center',
  },
  R5__toolbar__tool_trim__lbl: {
    position: 'absolute',
    left: 0,
    top: 40,
    width: 78,
    fontSize: 11,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R5__toolbar__tool_draw: {
    position: 'absolute',
    left: 164,
    top: 8,
    width: 78,
    height: 60,
  },
  R5__toolbar__tool_draw__icon_bg: {
    position: 'absolute',
    left: 25,
    top: 6,
    width: 28,
    height: 28,
    backgroundColor: '#F4EFE6',
    borderRadius: 14,
  },
  R5__toolbar__tool_draw__icon_bg__ico: {
    position: 'absolute',
    left: 0,
    top: 6,
    width: 28,
    fontSize: 15,
    color: '#0F5D45',
    textAlign: 'center',
  },
  R5__toolbar__tool_draw__lbl: {
    position: 'absolute',
    left: 0,
    top: 40,
    width: 78,
    fontSize: 11,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R5__toolbar__tool_move: {
    position: 'absolute',
    left: 242,
    top: 8,
    width: 78,
    height: 60,
  },
  R5__toolbar__tool_move__icon_bg: {
    position: 'absolute',
    left: 25,
    top: 6,
    width: 28,
    height: 28,
    backgroundColor: '#F4EFE6',
    borderRadius: 14,
  },
  R5__toolbar__tool_move__icon_bg__ico: {
    position: 'absolute',
    left: 0,
    top: 6,
    width: 28,
    fontSize: 15,
    color: '#0F5D45',
    textAlign: 'center',
  },
  R5__toolbar__tool_move__lbl: {
    position: 'absolute',
    left: 0,
    top: 40,
    width: 78,
    fontSize: 11,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R5__btn_preview: {
    position: 'absolute',
    left: 24,
    top: 646,
    width: 327,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R5__btn_preview__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R6__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R6__title: {
    position: 'absolute',
    left: 0,
    top: 56,
    width: 375,
    fontSize: 17,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R6__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 460,
    backgroundColor: '#E8E3D3',
  },
  R6__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 220,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R6__hint_card: {
    position: 'absolute',
    left: 24,
    top: 570,
    width: 327,
    height: 60,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R6__hint_card__line1: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 13,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R6__hint_card__line2: {
    position: 'absolute',
    left: 0,
    top: 32,
    width: 327,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R6__btn_path: {
    position: 'absolute',
    left: 24,
    top: 646,
    width: 156,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R6__btn_path__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 156,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R6__btn_erase: {
    position: 'absolute',
    left: 194,
    top: 646,
    width: 156,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: '#143D35',
    borderRadius: 22,
  },
  R6__btn_erase__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 156,
    fontSize: 14,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R7__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R7__title: {
    position: 'absolute',
    left: 0,
    top: 56,
    width: 375,
    fontSize: 17,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R7__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 460,
    backgroundColor: '#E8E3D3',
  },
  R7__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 220,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R7__hint_card: {
    position: 'absolute',
    left: 24,
    top: 570,
    width: 327,
    height: 60,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R7__hint_card__line1: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 13,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R7__hint_card__line2: {
    position: 'absolute',
    left: 0,
    top: 32,
    width: 327,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R7__btn_path: {
    position: 'absolute',
    left: 24,
    top: 646,
    width: 156,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R7__btn_path__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 156,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R7__btn_erase: {
    position: 'absolute',
    left: 194,
    top: 646,
    width: 156,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: '#143D35',
    borderRadius: 22,
  },
  R7__btn_erase__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 156,
    fontSize: 14,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R8__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R8__title: {
    position: 'absolute',
    left: 0,
    top: 56,
    width: 375,
    fontSize: 17,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R8__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 460,
    backgroundColor: '#E8E3D3',
  },
  R8__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 220,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R8__hint_card: {
    position: 'absolute',
    left: 24,
    top: 570,
    width: 327,
    height: 60,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R8__hint_card__line1: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 13,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R8__hint_card__line2: {
    position: 'absolute',
    left: 0,
    top: 32,
    width: 327,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R8__btn_apply: {
    position: 'absolute',
    left: 24,
    top: 646,
    width: 327,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R8__btn_apply__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
  R9__back: {
    position: 'absolute',
    left: 16,
    top: 50,
    fontSize: 30,
    color: '#143D35',
    fontWeight: '500',
  },
  R9__title: {
    position: 'absolute',
    left: 0,
    top: 56,
    width: 375,
    fontSize: 17,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R9__map_preview: {
    position: 'absolute',
    left: 0,
    top: 90,
    width: 375,
    height: 460,
    backgroundColor: '#E8E3D3',
  },
  R9__map_preview__map_note: {
    position: 'absolute',
    left: 0,
    top: 220,
    width: 375,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
  },
  R9__hint_card: {
    position: 'absolute',
    left: 24,
    top: 570,
    width: 327,
    height: 60,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 16,
  },
  R9__hint_card__line1: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 327,
    fontSize: 13,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
  },
  R9__hint_card__line2: {
    position: 'absolute',
    left: 0,
    top: 32,
    width: 327,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
  },
  R9__btn_reset: {
    position: 'absolute',
    left: 24,
    top: 646,
    width: 156,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: '#143D35',
    borderRadius: 22,
  },
  R9__btn_reset__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 156,
    fontSize: 14,
    color: '#143D35',
    fontWeight: '700',
    textAlign: 'center',
  },
  R9__btn_done: {
    position: 'absolute',
    left: 194,
    top: 646,
    width: 156,
    height: 44,
    backgroundColor: '#143D35',
    borderRadius: 22,
  },
  R9__btn_done__lbl: {
    position: 'absolute',
    left: 0,
    top: 12,
    width: 156,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
  },
});