import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shared__fern_accent: {
    position: 'absolute',
    left: -20,
    top: 620,
    width: 130,
    height: 190,
  },
  shared__leaf_accent: {
    position: 'absolute',
    left: 265,
    top: 640,
    width: 130,
    height: 170,
  },
  A0__scrim: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 375,
    height: 812,
    backgroundColor: 'rgba(245,235,211,0.55)',
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A0__hero_cairn: {
    position: 'absolute',
    left: 107,
    top: 130,
    width: 160,
    height: 200,
  },
  A0__wordmark: {
    position: 'absolute',
    left: 27,
    top: 342,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '800',
    letterSpacing: 1.5,
    textAlign: 'center',
    width: 320,
  },
  A0__tagline: {
    position: 'absolute',
    left: 27,
    top: 380,
    fontSize: 14,
    color: '#65706A',
    fontWeight: '500',
    textAlign: 'center',
    width: 320,
  },
  A0__btn_apple: {
    position: 'absolute',
    left: 32,
    top: 500,
    width: 311,
    height: 52,
    backgroundColor: '#000000',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A0__btn_apple_label: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  A0__btn_google: {
    position: 'absolute',
    left: 32,
    top: 564,
    width: 311,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A0__btn_google_label: {
    color: '#202A25',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  A0__btn_email: {
    position: 'absolute',
    left: 32,
    top: 628,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A0__btn_email_label: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  A1__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  A1__title: {
    position: 'absolute',
    left: 32,
    top: 130,
    fontSize: 26,
    color: '#202A25',
    fontWeight: '700',
  },
  A1__title_2: {
    position: 'absolute',
    left: 32,
    top: 162,
    fontSize: 26,
    color: '#202A25',
    fontWeight: '700',
  },
  A1__btn_apple: {
    position: 'absolute',
    left: 32,
    top: 300,
    width: 311,
    height: 56,
    backgroundColor: '#000000',
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A1__btn_apple_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A1__btn_google: {
    position: 'absolute',
    left: 32,
    top: 368,
    width: 311,
    height: 56,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A1__btn_google_label: {
    color: '#202A25',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A1__btn_email: {
    position: 'absolute',
    left: 32,
    top: 436,
    width: 311,
    height: 56,
    backgroundColor: '#143D35',
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A1__btn_email_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A1__signin_link: {
    position: 'absolute',
    left: 27,
    top: 520,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  A2__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  A2__title: {
    position: 'absolute',
    left: 32,
    top: 110,
    fontSize: 24,
    color: '#202A25',
    fontWeight: '700',
  },
  A2__subtitle: {
    position: 'absolute',
    left: 32,
    top: 144,
    fontSize: 14,
    color: '#65706A',
  },
  A2__label_email: {
    position: 'absolute',
    left: 32,
    top: 200,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  A2__field_email: {
    position: 'absolute',
    left: 32,
    top: 220,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A2__field_email__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  A2__label_pass: {
    position: 'absolute',
    left: 32,
    top: 288,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  A2__field_pass: {
    position: 'absolute',
    left: 32,
    top: 308,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A2__field_pass__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  A2__req_1: {
    position: 'absolute',
    left: 32,
    top: 372,
    fontSize: 12,
    color: '#65706A',
  },
  A2__req_2: {
    position: 'absolute',
    left: 32,
    top: 392,
    fontSize: 12,
    color: '#65706A',
  },
  A2__req_3: {
    position: 'absolute',
    left: 32,
    top: 412,
    fontSize: 12,
    color: '#65706A',
  },
  A2__btn_continue: {
    position: 'absolute',
    left: 32,
    top: 470,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A2__btn_continue_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A2__signin_link: {
    position: 'absolute',
    left: 27,
    top: 550,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  A3__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  A3__icon_mail: {
    position: 'absolute',
    left: 163,
    top: 100,
    width: 48,
    height: 48,
  },
  A3__title: {
    position: 'absolute',
    left: 27,
    top: 160,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  A3__subtitle: {
    position: 'absolute',
    left: 27,
    top: 195,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  A3__subtitle_2: {
    position: 'absolute',
    left: 27,
    top: 213,
    fontSize: 13,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__otp_1: {
    position: 'absolute',
    left: 47,
    top: 260,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__otp_2: {
    position: 'absolute',
    left: 99,
    top: 260,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__otp_3: {
    position: 'absolute',
    left: 151,
    top: 260,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__otp_4: {
    position: 'absolute',
    left: 203,
    top: 260,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__otp_5: {
    position: 'absolute',
    left: 255,
    top: 260,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__otp_6: {
    position: 'absolute',
    left: 307,
    top: 260,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__resend: {
    position: 'absolute',
    left: 27,
    top: 330,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_1: {
    position: 'absolute',
    left: 47,
    top: 386,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_1__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_2: {
    position: 'absolute',
    left: 143,
    top: 386,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_2__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_3: {
    position: 'absolute',
    left: 239,
    top: 386,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_3__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_4: {
    position: 'absolute',
    left: 47,
    top: 450,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_4__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_5: {
    position: 'absolute',
    left: 143,
    top: 450,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_5__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_6: {
    position: 'absolute',
    left: 239,
    top: 450,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_6__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_7: {
    position: 'absolute',
    left: 47,
    top: 514,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_7__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_8: {
    position: 'absolute',
    left: 143,
    top: 514,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_8__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_9: {
    position: 'absolute',
    left: 239,
    top: 514,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_9__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_0: {
    position: 'absolute',
    left: 143,
    top: 578,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_0__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__keypad_del: {
    position: 'absolute',
    left: 239,
    top: 578,
    width: 90,
    height: 56,
    backgroundColor: '#F9F1DC',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A3__keypad_del__n: {
    position: 'absolute',
    left: -115,
    top: 18,
    fontSize: 22,
    color: '#65706A',
    fontWeight: '600',
    textAlign: 'center',
    width: 320,
  },
  A3__btn_continue: {
    position: 'absolute',
    left: 32,
    top: 680,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A3__btn_continue_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A4__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  A4__title: {
    position: 'absolute',
    left: 32,
    top: 110,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
  },
  A4__label_name: {
    position: 'absolute',
    left: 32,
    top: 180,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  A4__field_name: {
    position: 'absolute',
    left: 32,
    top: 200,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A4__field_name__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  A4__label_dob: {
    position: 'absolute',
    left: 32,
    top: 268,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  A4__field_dob: {
    position: 'absolute',
    left: 32,
    top: 288,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A4__field_dob__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  A4__btn_continue: {
    position: 'absolute',
    left: 32,
    top: 720,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A4__btn_continue_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A5__check_circle: {
    position: 'absolute',
    left: 139,
    top: 260,
    width: 96,
    height: 96,
    backgroundColor: '#3E7B57',
    borderRadius: 48,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  A5__check_circle__tick: {
    position: 'absolute',
    left: -112,
    top: 24,
    fontSize: 46,
    color: '#FFFFFF',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  A5__title: {
    position: 'absolute',
    left: 27,
    top: 388,
    fontSize: 24,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  A5__subtitle: {
    position: 'absolute',
    left: 27,
    top: 424,
    fontSize: 15,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  A5__btn_go: {
    position: 'absolute',
    left: 32,
    top: 700,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  A5__btn_go_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  A6__eyebrow: {
    position: 'absolute',
    left: 210,
    top: 90,
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '700',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  A6__line_1: {
    position: 'absolute',
    left: 210,
    top: 110,
    fontSize: 13,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  A6__km: {
    position: 'absolute',
    left: 210,
    top: 132,
    fontSize: 32,
    color: '#FFFFFF',
    fontWeight: '800',
    textShadowColor: 'rgba(0,0,0,0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  A6__loc: {
    position: 'absolute',
    left: 210,
    top: 174,
    fontSize: 13,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  R0__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  R0__title: {
    position: 'absolute',
    left: 32,
    top: 110,
    fontSize: 24,
    color: '#202A25',
    fontWeight: '700',
  },
  R0__subtitle: {
    position: 'absolute',
    left: 32,
    top: 144,
    fontSize: 14,
    color: '#65706A',
  },
  R0__label_email: {
    position: 'absolute',
    left: 32,
    top: 200,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  R0__field_email: {
    position: 'absolute',
    left: 32,
    top: 220,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  R0__field_email__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  R0__label_pass: {
    position: 'absolute',
    left: 32,
    top: 288,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  R0__field_pass: {
    position: 'absolute',
    left: 32,
    top: 308,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  R0__field_pass__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  R0__forgot: {
    position: 'absolute',
    left: 220,
    top: 366,
    width: 123,
    fontSize: 12,
    color: '#143D35',
    fontWeight: '600',
    textAlign: 'right',
  },
  R0__btn_signin: {
    position: 'absolute',
    left: 32,
    top: 420,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  R0__btn_signin_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  R0__signup_link: {
    position: 'absolute',
    left: 27,
    top: 500,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  R1__cairn_hero: {
    position: 'absolute',
    left: 107,
    top: 280,
    width: 160,
    height: 200,
  },
  R1__restoring: {
    position: 'absolute',
    left: 27,
    top: 510,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  R2__eyebrow: {
    position: 'absolute',
    left: 210,
    top: 90,
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '700',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  R2__line_1: {
    position: 'absolute',
    left: 210,
    top: 110,
    fontSize: 13,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  R2__km: {
    position: 'absolute',
    left: 210,
    top: 132,
    fontSize: 32,
    color: '#FFFFFF',
    fontWeight: '800',
    textShadowColor: 'rgba(0,0,0,0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  R2__loc: {
    position: 'absolute',
    left: 210,
    top: 174,
    fontSize: 13,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  R3__icon_lock: {
    position: 'absolute',
    left: 155,
    top: 220,
    width: 64,
    height: 64,
  },
  R3__title: {
    position: 'absolute',
    left: 27,
    top: 320,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  R3__subtitle: {
    position: 'absolute',
    left: 27,
    top: 354,
    fontSize: 14,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  R3__btn_signin: {
    position: 'absolute',
    left: 32,
    top: 500,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  R3__btn_signin_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  PR0__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  PR0__plane: {
    position: 'absolute',
    left: 27,
    top: 130,
    fontSize: 44,
    color: '#143D35',
    textAlign: 'center',
    width: 320,
  },
  PR0__title: {
    position: 'absolute',
    left: 27,
    top: 200,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  PR0__subtitle: {
    position: 'absolute',
    left: 27,
    top: 236,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  PR0__label_email: {
    position: 'absolute',
    left: 32,
    top: 300,
    fontSize: 12,
    color: '#202A25',
    fontWeight: '600',
  },
  PR0__field_email: {
    position: 'absolute',
    left: 32,
    top: 320,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR0__field_email__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  PR0__btn_send: {
    position: 'absolute',
    left: 32,
    top: 400,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  PR0__btn_send_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  PR0__back_link: {
    position: 'absolute',
    left: 27,
    top: 476,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  PR1__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  PR1__icon_mail: {
    position: 'absolute',
    left: 163,
    top: 100,
    width: 48,
    height: 48,
  },
  PR1__title: {
    position: 'absolute',
    left: 27,
    top: 160,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  PR1__subtitle: {
    position: 'absolute',
    left: 27,
    top: 196,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  PR1__otp_1: {
    position: 'absolute',
    left: 47,
    top: 246,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__otp_2: {
    position: 'absolute',
    left: 99,
    top: 246,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__otp_3: {
    position: 'absolute',
    left: 151,
    top: 246,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__otp_4: {
    position: 'absolute',
    left: 203,
    top: 246,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__otp_5: {
    position: 'absolute',
    left: 255,
    top: 246,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__otp_6: {
    position: 'absolute',
    left: 307,
    top: 246,
    width: 44,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__field_newp: {
    position: 'absolute',
    left: 32,
    top: 322,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__field_newp__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  PR1__field_conf: {
    position: 'absolute',
    left: 32,
    top: 380,
    width: 311,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9CFB6',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR1__field_conf__ph: {
    position: 'absolute',
    left: 16,
    top: 15,
    fontSize: 15,
    color: '#8A8579',
  },
  PR1__btn_reset: {
    position: 'absolute',
    left: 32,
    top: 452,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  PR1__btn_reset_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  PR1__back_link: {
    position: 'absolute',
    left: 27,
    top: 528,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  PR2__back: {
    position: 'absolute',
    left: 20,
    top: 56,
    fontSize: 30,
    color: '#202A25',
    fontWeight: '400',
  },
  PR2__x_circle: {
    position: 'absolute',
    left: 151,
    top: 130,
    width: 72,
    height: 72,
    backgroundColor: '#B8402A',
    borderRadius: 36,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  PR2__x_circle__x: {
    position: 'absolute',
    left: -124,
    top: 18,
    fontSize: 32,
    color: '#FFFFFF',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  PR2__title: {
    position: 'absolute',
    left: 27,
    top: 232,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  PR2__subtitle: {
    position: 'absolute',
    left: 27,
    top: 266,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  PR2__timer: {
    position: 'absolute',
    left: 27,
    top: 294,
    fontSize: 12,
    color: '#8A8579',
    textAlign: 'center',
    width: 320,
  },
  PR2__btn_back: {
    position: 'absolute',
    left: 32,
    top: 450,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  PR2__btn_back_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  OS0__cloud_off: {
    position: 'absolute',
    left: 27,
    top: 190,
    fontSize: 68,
    color: '#8A8579',
    textAlign: 'center',
    width: 320,
  },
  OS0__title: {
    position: 'absolute',
    left: 27,
    top: 320,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  OS0__subtitle: {
    position: 'absolute',
    left: 27,
    top: 356,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  OS0__btn_retry: {
    position: 'absolute',
    left: 32,
    top: 470,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  OS0__btn_retry_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  OS1__shield: {
    position: 'absolute',
    left: 27,
    top: 190,
    fontSize: 64,
    color: '#143D35',
    textAlign: 'center',
    width: 320,
  },
  OS1__title: {
    position: 'absolute',
    left: 27,
    top: 320,
    fontSize: 22,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  OS1__subtitle: {
    position: 'absolute',
    left: 27,
    top: 356,
    fontSize: 13,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
  OS1__btn_back: {
    position: 'absolute',
    left: 32,
    top: 470,
    width: 311,
    height: 52,
    backgroundColor: '#143D35',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  OS1__btn_back_label: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  OS2__check_circle: {
    position: 'absolute',
    left: 139,
    top: 260,
    width: 96,
    height: 96,
    backgroundColor: '#3E7B57',
    borderRadius: 48,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  OS2__check_circle__tick: {
    position: 'absolute',
    left: -112,
    top: 24,
    fontSize: 46,
    color: '#FFFFFF',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  OS2__title: {
    position: 'absolute',
    left: 27,
    top: 388,
    fontSize: 24,
    color: '#202A25',
    fontWeight: '700',
    textAlign: 'center',
    width: 320,
  },
  OS2__subtitle: {
    position: 'absolute',
    left: 27,
    top: 424,
    fontSize: 15,
    color: '#65706A',
    textAlign: 'center',
    width: 320,
  },
});