import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shared__stats_strip: {
    position: 'absolute',
    left: 0,
    top: 44,
    width: 375,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  shared__stats_strip__stat_km: {
    position: 'absolute',
    left: 24,
    top: 12,
    fontSize: 14,
    color: '#1E2A24',
    fontWeight: '700',
  },
  shared__stats_strip__stat_time: {
    position: 'absolute',
    left: 118,
    top: 12,
    fontSize: 14,
    color: '#1E2A24',
    fontWeight: '700',
  },
  shared__stats_strip__stat_elev: {
    position: 'absolute',
    left: 220,
    top: 12,
    fontSize: 14,
    color: '#1E2A24',
    fontWeight: '600',
  },
  shared__stats_strip__stat_gps: {
    position: 'absolute',
    left: 302,
    top: 12,
    fontSize: 12,
    color: '#455D3C',
    fontWeight: '700',
  },
  shared__tab_bar: {
    position: 'absolute',
    left: 24,
    top: 730,
    width: 327,
    height: 62,
    backgroundColor: 'rgba(249,246,243,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.10)',
    borderRadius: 31,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  shared__tab_bar__tab_trails: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_icon: {
    width: 28,
    height: 28,
  },
  shared__tab_bar__tab_trails_icon_wrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_label: {
    color: '#0A1F17',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  shared__tab_bar__tab_friends: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_icon: {
    width: 28,
    height: 28,
  },
  shared__tab_bar__tab_friends_icon_wrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_label: {
    color: '#0A1F17',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  shared__tab_bar__tab_memory: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_icon: {
    width: 28,
    height: 28,
  },
  shared__tab_bar__tab_memory_icon_wrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_label: {
    color: '#0A1F17',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  shared__tab_bar__tab_settings: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_icon: {
    width: 28,
    height: 28,
  },
  shared__tab_bar__tab_settings_icon_wrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_label: {
    color: '#0A1F17',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  H0__free_hike_pill: {
    position: 'absolute',
    left: 18,
    top: 529,
    width: 338,
    height: 78,
    backgroundColor: 'rgba(249,246,243,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.10)',
    borderRadius: 18,
  },
  H0__free_hike_pill__pill_eyebrow: {
    position: 'absolute',
    left: 20,
    top: 14,
    fontSize: 12,
    color: '#1E2A24',
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  H0__free_hike_pill__pill_sub: {
    position: 'absolute',
    left: 20,
    top: 36,
    fontSize: 13,
    color: '#5F6B62',
    fontWeight: '500',
  },
  H0__free_hike_pill__pill_chev: {
    position: 'absolute',
    left: 305,
    top: 20,
    fontSize: 20,
    color: '#5F6B62',
    fontWeight: '700',
  },
  H0__route_row: {
    position: 'absolute',
    left: 18,
    top: 620,
    width: 338,
    height: 44,
    backgroundColor: 'rgba(249,246,243,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.08)',
    borderRadius: 12,
  },
  H0__route_row__route_lbl: {
    position: 'absolute',
    left: 16,
    top: 14,
    fontSize: 14,
    color: '#1E2A24',
    fontWeight: '600',
  },
  H0__route_row__route_chev: {
    position: 'absolute',
    left: 310,
    top: 10,
    fontSize: 22,
    color: '#8A8579',
    fontWeight: '500',
  },
  H0__start_hiking_btn: {
    position: 'absolute',
    left: 18,
    top: 676,
    width: 338,
    height: 52,
    backgroundColor: '#455D3C',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  H0__start_hiking_btn_label: {
    color: '#F9F6F3',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  H1__fab_compass: {
    position: 'absolute',
    left: 24,
    top: 640,
    width: 44,
    height: 44,
    backgroundColor: 'rgba(249,246,243,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.10)',
    borderRadius: 22,
  },
  H1__fab_compass__compass_glyph: {
    position: 'absolute',
    left: 12,
    top: 8,
    fontSize: 22,
    color: '#455D3C',
    fontWeight: '600',
  },
  H1__fab_layers: {
    position: 'absolute',
    left: 307,
    top: 640,
    width: 44,
    height: 44,
    backgroundColor: 'rgba(249,246,243,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.10)',
    borderRadius: 22,
  },
  H1__fab_layers__layers_glyph: {
    position: 'absolute',
    left: 12,
    top: 8,
    fontSize: 22,
    color: '#455D3C',
    fontWeight: '600',
  },
  H2__action_pause: {
    position: 'absolute',
    left: 60,
    top: 620,
    width: 60,
    height: 60,
    backgroundColor: '#455D3C',
    borderRadius: 30,
  },
  H2__action_pause__pause_glyph: {
    position: 'absolute',
    left: 20,
    top: 14,
    fontSize: 24,
    color: '#F9F6F3',
    fontWeight: '900',
  },
  H2__action_cairn: {
    position: 'absolute',
    left: 157,
    top: 600,
    width: 60,
    height: 60,
    backgroundColor: '#2F3F28',
    borderRadius: 30,
  },
  H2__action_cairn__cairn_icon: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 36,
    height: 36,
  },
  H2__action_lock: {
    position: 'absolute',
    left: 255,
    top: 620,
    width: 60,
    height: 60,
    backgroundColor: '#455D3C',
    borderRadius: 30,
  },
  H2__action_lock__lock_glyph: {
    position: 'absolute',
    left: 16,
    top: 12,
    fontSize: 26,
    color: '#F9F6F3',
    fontWeight: '700',
  },
  H2__action_pause_lbl: {
    position: 'absolute',
    left: 60,
    top: 686,
    width: 60,
    fontSize: 11,
    color: '#1E2A24',
    fontWeight: '700',
    textAlign: 'center',
  },
  H2__action_cairn_lbl: {
    position: 'absolute',
    left: 130,
    top: 666,
    width: 114,
    fontSize: 11,
    color: '#1E2A24',
    fontWeight: '700',
    textAlign: 'center',
  },
  H2__action_lock_lbl: {
    position: 'absolute',
    left: 255,
    top: 686,
    width: 60,
    fontSize: 11,
    color: '#1E2A24',
    fontWeight: '700',
    textAlign: 'center',
  },
  H3__short_card: {
    position: 'absolute',
    left: 24,
    top: 220,
    width: 327,
    height: 400,
    backgroundColor: '#F9F6F3',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.10)',
    borderRadius: 22,
  },
  H3__short_card__short_eyebrow: {
    position: 'absolute',
    left: 24,
    top: 22,
    fontSize: 12,
    color: '#8A8579',
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  H3__short_card__short_title: {
    position: 'absolute',
    left: 24,
    top: 44,
    width: 279,
    fontSize: 22,
    color: '#1E2A24',
    fontWeight: '800',
    letterSpacing: -0.3,
    lineHeight: 28,
  },
  H3__short_card__short_km: {
    position: 'absolute',
    left: 24,
    top: 120,
    fontSize: 48,
    color: '#455D3C',
    fontWeight: '900',
    letterSpacing: -1.2,
  },
  H3__short_card__short_km_unit: {
    position: 'absolute',
    left: 130,
    top: 148,
    fontSize: 15,
    color: '#5F6B62',
    fontWeight: '600',
  },
  H3__short_card__short_time: {
    position: 'absolute',
    left: 24,
    top: 190,
    fontSize: 18,
    color: '#1E2A24',
    fontWeight: '700',
  },
  H3__short_card__short_elev: {
    position: 'absolute',
    left: 24,
    top: 218,
    fontSize: 14,
    color: '#5F6B62',
    fontWeight: '500',
  },
  H3__short_cta: {
    position: 'absolute',
    left: 32,
    top: 500,
    width: 311,
    height: 52,
    backgroundColor: '#455D3C',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  H3__short_cta_label: {
    color: '#F9F6F3',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  H3__short_secondary: {
    position: 'absolute',
    left: 32,
    top: 572,
    width: 311,
    fontSize: 15,
    color: '#5F6B62',
    fontWeight: '700',
    textAlign: 'center',
  },
  H4__complete_hero: {
    position: 'absolute',
    left: 0,
    top: 88,
    width: 375,
    height: 320,
  },
  H4__complete_title: {
    position: 'absolute',
    left: 24,
    top: 425,
    width: 327,
    fontSize: 24,
    color: '#1E2A24',
    fontWeight: '800',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  H4__complete_stats_row: {
    position: 'absolute',
    left: 24,
    top: 470,
    width: 327,
    height: 84,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  H4__complete_stats_row__stat1_val: {
    position: 'absolute',
    left: 6,
    top: 6,
    width: 100,
    fontSize: 30,
    color: '#455D3C',
    fontWeight: '900',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  H4__complete_stats_row__stat1_lbl: {
    position: 'absolute',
    left: 6,
    top: 44,
    width: 100,
    fontSize: 12,
    color: '#8A8579',
    fontWeight: '600',
    textAlign: 'center',
  },
  H4__complete_stats_row__stat2_val: {
    position: 'absolute',
    left: 113,
    top: 6,
    width: 100,
    fontSize: 30,
    color: '#455D3C',
    fontWeight: '900',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  H4__complete_stats_row__stat2_lbl: {
    position: 'absolute',
    left: 113,
    top: 44,
    width: 100,
    fontSize: 12,
    color: '#8A8579',
    fontWeight: '600',
    textAlign: 'center',
  },
  H4__complete_stats_row__stat3_val: {
    position: 'absolute',
    left: 220,
    top: 6,
    width: 100,
    fontSize: 30,
    color: '#455D3C',
    fontWeight: '900',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  H4__complete_stats_row__stat3_lbl: {
    position: 'absolute',
    left: 220,
    top: 44,
    width: 100,
    fontSize: 12,
    color: '#8A8579',
    fontWeight: '600',
    textAlign: 'center',
  },
  H4__save_hike_btn: {
    position: 'absolute',
    left: 24,
    top: 605,
    width: 327,
    height: 56,
    backgroundColor: '#455D3C',
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  H4__save_hike_btn_label: {
    color: '#F9F6F3',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  H4__discard_secondary: {
    position: 'absolute',
    left: 24,
    top: 675,
    width: 327,
    fontSize: 15,
    color: '#8A8579',
    fontWeight: '700',
    textAlign: 'center',
  },
});