import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shared__greeting_eyebrow: {
    position: 'absolute',
    left: 24,
    top: 52,
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '500',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  shared__greeting_name: {
    position: 'absolute',
    left: 24,
    top: 70,
    fontSize: 24,
    color: '#ffffff',
    fontWeight: '600',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  shared__avatar: {
    position: 'absolute',
    left: 311,
    top: 56,
    width: 44,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.85)',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__avatar_content: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '600',
  },
  shared__action_row: {
    position: 'absolute',
    left: 0,
    top: 460,
    width: 375,
    height: 108,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  shared__action_row__action_hiking: {
    position: 'absolute',
    left: 24,
    top: 0,
    width: 104,
    height: 108,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 0,
    borderColor: 'rgba(0,0,0,0)',
    borderRadius: 22,
  },
  shared__action_row__action_hiking__icon: {
    position: 'absolute',
    left: 32,
    top: 18,
    width: 40,
    height: 40,
  },
  shared__action_row__action_hiking__label: {
    position: 'absolute',
    left: 0,
    top: 68,
    width: 104,
    fontSize: 14,
    color: '#0A1F17',
    fontWeight: '600',
    textAlign: 'center',
  },
  shared__action_row__action_running: {
    position: 'absolute',
    left: 136,
    top: 0,
    width: 104,
    height: 108,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 0,
    borderColor: 'rgba(0,0,0,0)',
    borderRadius: 22,
  },
  shared__action_row__action_running__icon: {
    position: 'absolute',
    left: 32,
    top: 18,
    width: 40,
    height: 40,
  },
  shared__action_row__action_running__label: {
    position: 'absolute',
    left: 0,
    top: 68,
    width: 104,
    fontSize: 14,
    color: '#0A1F17',
    fontWeight: '600',
    textAlign: 'center',
  },
  shared__action_row__action_leave_cairn: {
    position: 'absolute',
    left: 248,
    top: 0,
    width: 104,
    height: 108,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 0,
    borderColor: 'rgba(0,0,0,0)',
    borderRadius: 22,
  },
  shared__action_row__action_leave_cairn__icon: {
    position: 'absolute',
    left: 32,
    top: 18,
    width: 40,
    height: 40,
  },
  shared__action_row__action_leave_cairn__label: {
    position: 'absolute',
    left: 0,
    top: 68,
    width: 104,
    fontSize: 13,
    color: '#0A1F17',
    fontWeight: '600',
    textAlign: 'center',
  },
  shared__tab_bar: {
    position: 'absolute',
    left: 24,
    top: 730,
    width: 327,
    height: 62,
    backgroundColor: 'rgba(247,243,234,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(20,42,30,0.12)',
    borderRadius: 31,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  shared__tab_bar__tab_trails: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_trails_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  shared__tab_bar__tab_friends: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_friends_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  shared__tab_bar__tab_memory: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_memory_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  shared__tab_bar__tab_settings: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_icon: {
    width: 30,
    height: 30,
  },
  shared__tab_bar__tab_settings_icon_wrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_label: {
    color: '#0A1F17',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  H0__hero_invite_1: {
    position: 'absolute',
    left: 24,
    top: 148,
    fontSize: 40,
    color: '#ffffff',
    fontWeight: '700',
    letterSpacing: -0.5,
    lineHeight: 46,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  H0__hero_invite_2: {
    position: 'absolute',
    left: 24,
    top: 194,
    fontSize: 40,
    color: '#ffffff',
    fontWeight: '700',
    letterSpacing: -0.5,
    lineHeight: 46,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  H0__hero_invite_sub: {
    position: 'absolute',
    left: 24,
    top: 252,
    fontSize: 15,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
    lineHeight: 20,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  H0__first_journey_card: {
    position: 'absolute',
    left: 24,
    top: 594,
    width: 327,
    height: 108,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    borderRadius: 20,
  },
  H0__first_journey_card__first_journey_eyebrow: {
    position: 'absolute',
    left: 20,
    top: 16,
    fontSize: 11,
    color: '#5F6B62',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  H0__first_journey_card__first_journey_title: {
    position: 'absolute',
    left: 20,
    top: 34,
    fontSize: 19,
    color: '#143D35',
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  H0__first_journey_card__first_journey_title2: {
    position: 'absolute',
    left: 20,
    top: 58,
    fontSize: 19,
    color: '#143D35',
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  H0__first_journey_card__first_journey_hint: {
    position: 'absolute',
    left: 20,
    top: 84,
    fontSize: 12,
    color: '#3F4A44',
    fontWeight: '500',
    letterSpacing: 0,
  },
  H1__hero_metric_eyebrow: {
    position: 'absolute',
    left: 24,
    top: 138,
    fontSize: 13,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
    letterSpacing: 0.2,
    textShadowColor: 'rgba(0,0,0,0.45)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  H1__hero_metric_number: {
    position: 'absolute',
    left: 24,
    top: 168,
    fontSize: 56,
    color: '#ffffff',
    fontWeight: '700',
    letterSpacing: -1.5,
    lineHeight: 60,
    textShadowColor: 'rgba(0,0,0,0.55)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 14,
  },
  H1__hero_metric_unit: {
    position: 'absolute',
    left: 24,
    top: 232,
    fontSize: 15,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
    textShadowColor: 'rgba(0,0,0,0.45)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  H1__last_hike_card: {
    position: 'absolute',
    left: 24,
    top: 594,
    width: 327,
    height: 108,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    borderRadius: 20,
  },
  H1__last_hike_card__last_hike_eyebrow: {
    position: 'absolute',
    left: 20,
    top: 16,
    fontSize: 11,
    color: '#8A8579',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  H1__last_hike_card__last_hike_title: {
    position: 'absolute',
    left: 20,
    top: 34,
    fontSize: 18,
    color: '#143D35',
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  H1__last_hike_card__last_hike_meta: {
    position: 'absolute',
    left: 20,
    top: 62,
    fontSize: 12,
    color: '#65706A',
    fontWeight: '400',
  },
  H1__last_hike_card__last_hike_thumb: {
    position: 'absolute',
    left: 235,
    top: 12,
    width: 84,
    height: 84,
  },
});
