import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shared__header_back: {
    position: 'absolute',
    left: 16,
    top: 54,
    width: 24,
    height: 24,
  },
  shared__header_title: {
    position: 'absolute',
    left: 27.5,
    top: 56,
    fontSize: 19,
    color: '#143D35',
    fontWeight: '700',
    width: 320,
    textAlign: 'center',
  },
  shared__header_add: {
    position: 'absolute',
    left: 335,
    top: 53,
    width: 26,
    height: 26,
  },
  shared__tabs: {
    position: 'absolute',
    left: 24,
    top: 101,
    width: 327,
    height: 34,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 17,
  },
  shared__tabs__friends_tab_hit: {
    position: 'absolute',
    left: 1,
    top: 1,
    width: 162,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tabs__friends_tab_hit_label: {
    color: '#143D35',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  shared__tabs__pending_tab_hit: {
    position: 'absolute',
    left: 164,
    top: 1,
    width: 162,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tabs__pending_tab_hit_label: {
    color: '#143D35',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  shared__add_friend_floating: {
    position: 'absolute',
    left: 68,
    top: 650,
    width: 239,
    height: 48,
    backgroundColor: '#0F5D45',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  shared__add_friend_floating_label: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  shared__add_friend_floating_icon: {
    position: 'absolute',
    left: 20,
    top: 12,
    width: 24,
    height: 24,
  },
  shared__tab_bar: {
    position: 'absolute',
    left: 0,
    top: 727,
    width: 375,
    height: 85,
    backgroundColor: 'rgba(255,253,248,0.82)',
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 200,
  },
  shared__tab_bar__tab_trails: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_icon: {
    width: 22,
    height: 22,
    tintColor: '#143D35',
  },
  shared__tab_bar__tab_trails_icon_wrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_trails_label: {
    color: '#143D35',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  shared__tab_bar__tab_friends: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_icon: {
    width: 22,
    height: 22,
    tintColor: '#0F5D45',
  },
  shared__tab_bar__tab_friends_icon_wrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_friends_label: {
    color: '#0F5D45',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  shared__tab_bar__tab_memory: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_icon: {
    width: 22,
    height: 22,
    tintColor: '#143D35',
  },
  shared__tab_bar__tab_memory_icon_wrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_memory_label: {
    color: '#143D35',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  shared__tab_bar__tab_settings: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_icon: {
    width: 22,
    height: 22,
    tintColor: '#143D35',
  },
  shared__tab_bar__tab_settings_icon_wrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shared__tab_bar__tab_settings_label: {
    color: '#143D35',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  F0__empty_title: {
    position: 'absolute',
    left: 27.5,
    top: 226,
    fontSize: 17,
    color: '#143D35',
    fontWeight: '700',
    width: 320,
    textAlign: 'center',
  },
  F0__empty_body: {
    position: 'absolute',
    left: 27.5,
    top: 255,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '400',
    width: 320,
    textAlign: 'center',
  },
  F0__empty_cairn: {
    position: 'absolute',
    left: 135,
    top: 310,
    width: 105,
    height: 105,
  },
  F1__friends_section_title: {
    position: 'absolute',
    left: 24,
    top: 158,
    fontSize: 13,
    color: '#143D35',
    fontWeight: '700',
  },
  F1__friends_list: {
    position: 'absolute',
    left: 20,
    top: 181,
    width: 335,
    height: 324,
    backgroundColor: 'rgba(255,255,255,0.00)',
    borderRadius: 0,
  },
  F1__friends_list__friend_row_template: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 335,
    height: 62,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.90)',
    borderRadius: 15,
  },
  F1__friends_list__friend_row_template__avatar: {
    position: 'absolute',
    left: 14,
    top: 13,
    width: 36,
    height: 36,
    backgroundColor: '{friendColor}',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  F1__friends_list__friend_row_template__avatar_content: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  F1__friends_list__friend_row_template__name: {
    position: 'absolute',
    left: 64,
    top: 11,
    fontSize: 13,
    color: '#202A25',
    fontWeight: '700',
  },
  F1__friends_list__friend_row_template__meta: {
    position: 'absolute',
    left: 64,
    top: 32,
    fontSize: 10,
    color: '#65706A',
    fontWeight: '400',
  },
  F2__incoming_title: {
    position: 'absolute',
    left: 24,
    top: 158,
    fontSize: 13,
    color: '#143D35',
    fontWeight: '700',
  },
  F2__incoming_list: {
    position: 'absolute',
    left: 20,
    top: 181,
    width: 335,
    height: 126,
    backgroundColor: 'rgba(255,255,255,0.00)',
    borderRadius: 0,
  },
  F2__sent_title: {
    position: 'absolute',
    left: 24,
    top: 326,
    fontSize: 13,
    color: '#143D35',
    fontWeight: '700',
  },
  F2__sent_list: {
    position: 'absolute',
    left: 20,
    top: 349,
    width: 335,
    height: 126,
    backgroundColor: 'rgba(255,255,255,0.00)',
    borderRadius: 0,
  },
  F3__incoming_title: {
    position: 'absolute',
    left: 24,
    top: 158,
    fontSize: 13,
    color: '#143D35',
    fontWeight: '700',
  },
  F3__incoming_list: {
    position: 'absolute',
    left: 20,
    top: 181,
    width: 335,
    height: 190,
    backgroundColor: 'rgba(255,255,255,0.00)',
    borderRadius: 0,
  },
  F3__no_sent_note: {
    position: 'absolute',
    left: 24,
    top: 392,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '400',
  },
  F4__sent_title: {
    position: 'absolute',
    left: 24,
    top: 158,
    fontSize: 13,
    color: '#143D35',
    fontWeight: '700',
  },
  F4__sent_list: {
    position: 'absolute',
    left: 20,
    top: 181,
    width: 335,
    height: 190,
    backgroundColor: 'rgba(255,255,255,0.00)',
    borderRadius: 0,
  },
  F4__no_incoming_note: {
    position: 'absolute',
    left: 24,
    top: 392,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '400',
  },
  F5__pending_empty_title: {
    position: 'absolute',
    left: 27.5,
    top: 232,
    fontSize: 16,
    color: '#143D35',
    fontWeight: '700',
    width: 320,
    textAlign: 'center',
  },
  F5__pending_empty_body: {
    position: 'absolute',
    left: 27.5,
    top: 260,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '400',
    width: 320,
    textAlign: 'center',
  },
  F6__sheet_scrim: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 375,
    height: 812,
    backgroundColor: 'rgba(20,30,25,0.16)',
    borderRadius: 0,
  },
  F6__add_friend_sheet: {
    position: 'absolute',
    left: 0,
    top: 320,
    width: 375,
    height: 492,
    backgroundColor: '#F9F7EF',
    borderRadius: 28,
  },
  F6__add_friend_sheet__hero: {
    position: 'absolute',
    left: 20,
    top: 18,
    width: 335,
    height: 147,
  },
  F6__add_friend_sheet__mail_icon: {
    position: 'absolute',
    left: 171,
    top: 147,
    width: 32,
    height: 32,
  },
  F6__add_friend_sheet__title: {
    position: 'absolute',
    left: 27.5,
    top: 192,
    fontSize: 19,
    color: '#143D35',
    fontWeight: '700',
    width: 320,
    textAlign: 'center',
  },
  F6__add_friend_sheet__body: {
    position: 'absolute',
    left: 27.5,
    top: 222,
    fontSize: 11,
    color: '#65706A',
    fontWeight: '400',
    width: 320,
    textAlign: 'center',
  },
  F6__add_friend_sheet__email_input: {
    position: 'absolute',
    left: 24,
    top: 260,
    width: 327,
    height: 48,
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(224,219,210,0.95)',
    borderRadius: 14,
  },
  F6__add_friend_sheet__send_request: {
    position: 'absolute',
    left: 24,
    top: 322,
    width: 327,
    height: 48,
    backgroundColor: '#0F5D45',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  F6__add_friend_sheet__send_request_label: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  F6__add_friend_sheet__cancel: {
    position: 'absolute',
    left: 24,
    top: 382,
    width: 327,
    height: 42,
    backgroundColor: 'rgba(255,255,255,0.00)',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  F6__add_friend_sheet__cancel_label: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
});