// Auto-generated by spike/svg_to_rn.py
// Do not edit by hand.

import React from 'react';
// Individual tag imports resolved below.
import { Circle, Path, Rect, Svg } from 'react-native-svg';

// SvgAccept
export function SvgAccept({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Path d="m5 12 4 4L19 6" />
    </Svg>
  );
}

// SvgAdd
export function SvgAdd({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 5v14M5 12h14" />
    </Svg>
  );
}

// SvgBack
export function SvgBack({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Path d="m15 18-6-6 6-6" />
    </Svg>
  );
}

// SvgClock
export function SvgClock({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Circle cx="12" cy="12" r="9" />
      <Path d="M12 7v5l3 2" />
    </Svg>
  );
}

// SvgDecline
export function SvgDecline({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Path d="m6 6 12 12M18 6 6 18" />
    </Svg>
  );
}

// SvgFriends
export function SvgFriends({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Circle cx="9" cy="8" r="3" />
      <Path d="M3 20v-2a6 6 0 0 1 12 0v2" />
      <Path d="M16 6a3 3 0 0 1 0 6M18 20v-2a5 5 0 0 0-3-4.58" />
    </Svg>
  );
}

// SvgMail
export function SvgMail({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Rect x="3" y="5" width="18" height="14" rx="2" />
      <Path d="m3 7 9 6 9-6" />
    </Svg>
  );
}

// SvgMemory
export function SvgMemory({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Rect x="3" y="5" width="18" height="14" rx="2" />
      <Path d="m3 7 9 6 9-6" />
    </Svg>
  );
}

// SvgPeople
export function SvgPeople({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Circle cx="9" cy="8" r="3" />
      <Path d="M3 20v-2a6 6 0 0 1 12 0v2" />
      <Path d="M16 6a3 3 0 0 1 0 6M18 20v-2a5 5 0 0 0-3-4.58" />
    </Svg>
  );
}

// SvgSend
export function SvgSend({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M22 2 11 13" />
      <Path d="m22 2-7 20-4-9-9-4 20-7Z" />
    </Svg>
  );
}

// SvgSettings
export function SvgSettings({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Circle cx="12" cy="12" r="9" />
      <Path d="M12 7v5l3 2" />
    </Svg>
  );
}

// SvgTrails
export function SvgTrails({ size = 24, color, strokeWidth }: { size?: number; color?: string; strokeWidth?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color ?? '#143D35'} strokeWidth={strokeWidth ?? 1.75} strokeLinecap="round" strokeLinejoin="round">
      <Path d="m15 18-6-6 6-6" />
    </Svg>
  );
}

// Lookup by asset path (matches spec.json asset refs)
export const svgByAsset = {
  'accept.svg': SvgAccept,
  'add.svg': SvgAdd,
  'back.svg': SvgBack,
  'clock.svg': SvgClock,
  'decline.svg': SvgDecline,
  'friends.svg': SvgFriends,
  'mail.svg': SvgMail,
  'memory.svg': SvgMemory,
  'people.svg': SvgPeople,
  'send.svg': SvgSend,
  'settings.svg': SvgSettings,
  'trails.svg': SvgTrails,
} as const;