-- seed_mock_users.sql — Friend System v1 / Sprint 67 / STORY-00527
--
-- Seeds 9 mock @cairn.demo accounts with bcrypt(cost=12) hashes generated by
-- backend/scripts/seed/gen_bcrypt_hashes.js. Passwords are single-character
-- (auth.js login does not enforce length — confirmed STORY-00524).
--
-- Mock matrix per FINAL_PRODUCT_PLAN_v4.md §8:
--   1@..6@ = Alice, Bob, Carol(stranger→friend), Dave(empty), LDY(rich), Eve(paywall)
--   x1@..x3@ = Stranger 1 (single mark near 9163 Back Loop), Stranger 2 (heatmap),
--              Stranger 3 (chain)
--
-- v4.V binding: 9163 (id=4) initial state = 0 friends, 0 subscriptions.
-- This script must NOT touch user_id=4, the friends table, or memory_subscriptions.
--
-- Idempotent: INSERT IGNORE skips rows that already exist by unique email.
-- To re-seed: run clear_mock_data.sql first, then this file.

USE cairn;

-- Sanity guard: refuse to run if a non-mock account has @cairn.demo email
-- (defense-in-depth — should never trigger, but blocks the script from
-- promoting a real user into the mock filter set).
SET @bad := (SELECT COUNT(*) FROM users
             WHERE email LIKE '%@cairn.demo' AND id < 0);
-- (kept as a placeholder; users.id is always > 0; statement is a no-op
-- intentionally — exists to remind future maintainers of the invariant.)

-- ──────────────────────────────────────────────────────────────────────────
-- 1. Mock users (9 rows)
-- ──────────────────────────────────────────────────────────────────────────

INSERT IGNORE INTO users (name, email, password_hash, account_type, memory_subscription_limit) VALUES
  ('Alice',      '1@cairn.demo',  '$2b$12$nWhlxif457QhXM4uLwkm9.hjLYxDDuAwTMXH6.Z8QPIoqsmWnaAuW', 'free', 5),
  ('Bob',        '2@cairn.demo',  '$2b$12$cEo7361SzjhgMjZZJZrT3uQK6mO2oShYYA6qzJaIy8w3f8Z08COWm', 'free', 5),
  ('Carol',      '3@cairn.demo',  '$2b$12$.HhlNyLSO8cNnX.0OfewruEWNk4VdvOaQCrt1VYjJzwiCTJb6q1ia', 'free', 5),
  ('Dave',       '4@cairn.demo',  '$2b$12$Ux./ROsRTHTZsY1U0z/laOehoSgCmSdl0IbzqKuMwj4IDtlgoqMJG', 'free', 5),
  ('LDY',        '5@cairn.demo',  '$2b$12$JKAKsFq9LCz4SK0OrsH59OXawsmv05kgBJZcomzv0wweMydBiLi7a', 'free', 5),
  ('Eve',        '6@cairn.demo',  '$2b$12$l3dkUG3ZMPpUwMXlxPrZQeNgQx/Xcro3Wbj0Kx8W702yNu6uXBqV6', 'free', 5),
  ('Stranger 1', 'x1@cairn.demo', '$2b$12$9EAKB0F6Mfq1ljhF/ZBSIuRDWlsWjcxQg63o/RJTO.1snJUCiITMG', 'free', 5),
  ('Stranger 2', 'x2@cairn.demo', '$2b$12$LuRsfVFOg89IoICAdsnic.0dPbCPPisxcb15wN8pMveF7haZ4d2Xm', 'free', 5),
  ('Stranger 3', 'x3@cairn.demo', '$2b$12$v3d.V5VmHiL2UREmyLCC0e4K9NR.WRRiNLLJze5SJeCUjYLoIj4ce', 'free', 5);

-- Verify count (informational only; will be 9 on a clean apply, less on idempotent re-run)
SELECT COUNT(*) AS mock_users_total FROM users WHERE email LIKE '%@cairn.demo';
